package xyz.iwolfking.woldsvaults.datagen;

import net.minecraft.data.DataGenerator;
import net.minecraftforge.common.data.LanguageProvider;
import xyz.iwolfking.woldsvaults.WoldsVaults;
import xyz.iwolfking.woldsvaults.init.ModItems;

public class ModLanguageProvider extends LanguageProvider {

    public ModLanguageProvider(DataGenerator gen) {
        super(gen, WoldsVaults.MOD_ID, "en_us");
    }

    @Override
    protected void addTranslations() {
        add("item.woldsvaults.rotten_heart", "Rotten Heart");
        add("item.woldsvaults.rotten_apple", "Rotten Apple");
        add("item.woldsvaults.verdant_globule", "Verdant Globule");
        add("item.woldsvaults.erratic_ember", "Erratic Ember");
        add("item.woldsvaults.refined_powder", "Refined Powder");
        add("item.woldsvaults.auric_crystal", "Auric Crystal");
        add("curios.identifier.shard_pouch", "Shard Pouch");
        add("curios.identifier.trinket_pouch", "Trinket Pouch");
        add("curios.identifier.green_trinket", "Green Trinket");
        add("curios.modifiers.trinket_pouch", "Pouch Modifiers");
        add("ftbquests.task.woldsvaults.vault_level", "Vault Level");
        add("ftbquests.task.woldsvaults.enter_vault", "Enter Vault");
        add("ftbquests.task.woldsvaults.complete_bounty", "Complete Bounty");
        add("item.scannable.vault_ores_module", "Scanner Module: Vault Ores");
        add("item.scannable.vault_chests_module", "Scanner Module: All Chests");
        add("item.scannable.vault_chests_module_living", "Scanner Module: Living Chests");
        add("item.scannable.vault_chests_module_gilded", "Scanner Module: Gilded Chests");
        add("item.scannable.vault_chests_module_ornate", "Scanner Module: Ornate Chests");
        add("item.scannable.vault_chests_module_raw", "Scanner Module: Raw Chests");
        add("item.scannable.vault_chests_module_wooden", "Scanner Module: Wooden Chests");
        add("item.scannable.vault_chests_module_treasure", "Scanner Module: Treasure Chests");
        add("item.scannable.vault_coins_module", "Scanner Module: Coin Stacks");
        add("item.scannable.vault_doors_module", "Scanner Module: Vault Doors");
        add("item.scannable.vault_objectives_module", "Scanner Module: Vault Objectives");
        add("item.scannable.vault_spirit_module", "Scanner Module: Vault Spirits");
        add("item.scannable.vault_cake_module", "Scanner Module: Vault Cakes");
        add("item.scannable.vault_treasure_doors_module", "Scanner Module: Treasure Doors");
        add("item.scannable.vault_dungeon_doors_module", "Scanner Module: Dungeon Doors");
        add("item.scannable.vault_vendoors_module", "Scanner Module: Vendoors");
        add("item.scannable.vault_pylon_module", "Scanner Module: Pylons");
        add("item.the_vault.crystal_seal_unhinged", "Seal of the Psychopath");
        add("item.the_vault.crystal_seal_doomsayer", "Seal of the Doomsayer");
        add("item.the_vault.crystal_seal_spirits", "Seal of the Exorcist");
        add("item.the_vault.crystal_seal_enchanter", "Seal of the Enchanter");
        add("item.the_vault.crystal_seal_titan", "Seal of the Titan");
        add("item.the_vault.crystal_seal_monolith", "Seal of the Searcher");
        add("item.the_vault.plushie", "Vault Plushie");
        add("item.the_vault.loot_sack", "Vault Sack");
        add("item.the_vault.rang", "Vaultarang");
        add("item.woldsvaults.weapon_augmenter", "Weapon Augmenter");
        add("item.woldsvaults.greedy_vault_rock", "Greedy Vault Rock");
        add("jei.the_vault.completion_crate_unhinged_scavenger_loot", "Unhinged Scavenger Crate");
        add("jei.the_vault.completion_crate_haunted_braziers_loot", "Haunted Braziers Crate");
        add("jei.the_vault.completion_crate_enchanted_elixir_loot", "Enchanted Elixir Crate");
        add("jei.the_vault.completion_crate_zealot_loot", "Zealot Crate");
        add("jei.the_vault.completion_crate_bingo_wold_loot", "Bingo Crate");
        add("jei.the_vault.completion_crate_ballistic_bingo_loot", "Ballistic Bingo Crate");
        add("jei.the_vault.completion_crate_ballistic_bingo_full_loot", "Ballistic Bingo Crate (Full)");
        add("jei.the_vault.completion_crate_bingo_wold_full_loot", "Bingo Crate (Full)");
        add("jei.the_vault.digsite_sand_loot", "Digsite Sand");
        add("jei.the_vault.iskallian_leaves_loot", "Woldian Leaves");
        add("jei.the_vault.hellish_sand_loot", "Hellish Sand");
        add("jei.the_vault.vendor_pedestal_loot", "Vendor Pedestal");
        add("jei.the_vault.dungeon_pedestal_loot", "Dungeon Pedestal");
        add("jei.the_vault.treasure_pedestal_loot", "Treasure Pedestal");
        add("item.the_vault.gem_iskallium", "§5Woldium Gem");
        add("item.the_vault.key_iskallium", "§5Woldium Key");
        add("item.the_vault.cluster_iskallium", "§5Woldium Cluster");
        add("item.the_vault.chunk_iskallium", "§5Woldium Chunk");
        add("block.the_vault.ore_iskallium", "§5Woldium Ore");
        add("block.the_vault.ore_iskallium_stone", "§5Woldium Ore - Stone");
        add("block.the_vault.ore_iskallium_vault_stone", "§5Woldium Ore - Vault Stone");
        add("block.the_vault.ore_iskallium_white", "§5Woldium Ore - Diorite");
        add("block.the_vault.treasure_door_iskallium", "§5Woldium Treasure Door");
        add("item.the_vault.tool.ravager", "Ravager");
        add("item.the_vault.tool.raker", "Raker");
        add("item.the_vault.tool.none", "Stick");
        add("block.the_vault.vault_salvager", "Vault Salvager");
        add("block.woldsvaults.dungeon_pedestal", "Dungeon Pedestal");
        add("block.woldsvaults.iskallian_leaves", "Woldian Leaves");
        add("block.woldsvaults.hellish_sand", "Hellish Sand");
        add("item.the_vault.gem_box", "Gem Box");
        add("item.the_vault.supply_box", "Supply Box");
        add("item.the_vault.augment_box", "Augment Box");
        add("item.woldsvaults.inscription_box", "Inscription Box");
        add("item.woldsvaults.omega_box", "Omega Box");
        add("item.woldsvaults.catalyst_box", "Catalyst Box");
        add("item.woldsvaults.enigma_egg", "Enigma Egg");
        add("item.woldsvaults.zephyr_charm", "Zephyr Charm");
        add("item.woldsvaults.augment_piece", "Augment Piece");
        add("item.the_vault.scavenger_benitoite_gemstone", "Benitoite Gemstone");
        add("item.the_vault.scavenger_wutodic_gemstone", "Wutodic Gemstone");
        add("item.the_vault.scavenger_echoing_gemstone", "Echoing Gemstone");
        add("item.the_vault.scavenger_pogging_gemstone", "Pogging Gemstone");
        add("item.the_vault.scavenger_ender_heart", "Enderman Heart");
        add("item.the_vault.scavenger_enderman_eye", "Enderman Eye");
        add("item.the_vault.scavenger_ender_crystal", "Ender Crystal");
        add("item.the_vault.scavenger_ender_artifact", "Ender Artifact");
        add("item.the_vault.altar_recatalyzer", "Altar Recatalyzer");
        add("item.woldsvaults.expertise_orb", "Expertise Orb");
        add("item.woldsvaults.skill_orb", "Skill Orb");
        add("item.woldsvaults.chromatic_iron_angel_ring", "Chromatic Iron Angel Ring");
        add("item.woldsvaults.chromatic_gold_angel_ring", "Chromatic Gold Angel Ring");
        add("item.woldsvaults.chromatic_steel_angel_ring", "Chromatic Steel Angel Ring");
        add("item.woldsvaults.black_chromatic_steel_angel_ring", "Black Chromatic Steel Angel Ring");
        add("item.woldsvaults.prismatic_angel_ring", "Prismatic Angel Ring");
        add("item.woldsvaults.crystal_seal_corrupt", "Seal of the Unknown");
        add("item.woldsvaults.ruined_essence", "Ruined Essence");
        add("item.woldsvaults.nullite_fragment", "Nullite Fragment");
        add("item.woldsvaults.nullite_crystal", "Nullite Crystal");
        add("item.woldsvaults.obelisk_resonator", "Obelisk Resonator");
        add("block.woldsvaults.scavenger_altar", "Deco Scavenger Altar");
        add("block.woldsvaults.obelisk", "Deco Obelisk");
        add("block.woldsvaults.lodestone", "Deco Lodestone");
        add("block.woldsvaults.monolith", "Deco Brazier");
        add("block.woldsvaults.mob_barrier_red", "Mob Barrier");
        add("block.woldsvaults.fractured_obelisk", "Fractured Obelisk");
        add("block.woldsvaults.monolith_controller", "Monolith Controller");
        add("block.woldsvaults.vault_crate_corrupt", "Corrupted Vault Crate");
        add("block.woldsvaults.vault_crate_alchemy", "Alchemy Vault Crate");
        add("block.woldsvaults.nullite_ore", "Nullite Ore");
        add("block.woldsvaults.doll_dismantler", "Doll Blender");
        add("entity.the_vault.wold", "Wold");
        add("entity.woldsvaults.green_ghost", "Toxic Ghost");
        add("entity.woldsvaults.black_ghost", "Unholy Ghost");
        add("entity.woldsvaults.blue_ghost", "Chilly Ghost");
        add("entity.woldsvaults.brown_ghost", "Cursed Ghost");
        add("entity.woldsvaults.dark_blue_ghost", "Arcane Ghost");
        add("entity.woldsvaults.dark_gray_ghost", "Steel Ghost");
        add("entity.woldsvaults.dark_red_ghost", "Crimson Ghost");
        add("entity.woldsvaults.purple_ghost", "Enchanted Ghost");
        add("entity.woldsvaults.red_ghost", "Red Ghost");
        add("entity.woldsvaults.yellow_ghost", "Rapid Ghost");
        add("item.woldsvaults.wold_spawn_egg", "Wold Spawn Egg");
        add("item.woldsvaults.boogieman_spawn_egg", "Boogieman Spawn Egg");
        add("item.woldsvaults.monster_eye_spawn_egg", "Monster Eye Spawn Egg");
        add("item.woldsvaults.robot_spawn_egg", "Robot Spawn Egg");
        add("item.woldsvaults.blue_blaze_spawn_egg", "Blue Blaze Spawn Egg");
        add("item.woldsvaults.capstone_frenzy", "Frenzy Capstone");
        add("item.woldsvaults.capstone_prosperous", "Prosperous Capstone");
        add("item.woldsvaults.capstone_all_seeing_eye", "All Seeing Eye Capstone");
        add("item.woldsvaults.capstone_vendoors", "Vendoors Capstone");
        add("item.woldsvaults.capstone_enchanted", "Enchanted Capstone");
        add("item.woldsvaults.waxing_augmenter", "Waxing Augmenter");
        add("item.woldsvaults.waning_augmenter", "Waning Augmenter");
        add("item.woldsvaults.repair_augmenter", "Repair Augmenter");
        add("item.woldsvaults.crystal_reinforcement", "Prismatic Reinforcement");
        add("item.woldsvaults.resonating_reinforcement", "Resonating Reinforcement");
        add("item.woldsvaults.stylish_focus", "Stylish Focus");
        add("item.woldsvaults.chiseling_focus", "Chiseling Focus");
        add("item.woldsvaults.vault_rock_candy", "Vault Rock Candy");
        add("item.woldsvaults.hasty_pomegranate", "Hasty Pomegranate");
        add("item.woldsvaults.wisdom_fruit", "Wisdom Fruit");
        add("item.woldsvaults.uber_chaos_catalyst", "Unhinged Vault Rock");
        add("item.woldsvaults.vaultar_box", "Vaultar Box");
        add("item.woldsvaults.mercy_orb", "Merciful Orb");
        add("item.woldsvaults.general_decor_scroll", "Vault Deco Scroll");
        add("item.woldsvaults.extraordinary_pog_prism", "Extraordinary Pog Prism");
        add("item.woldsvaults.heart_of_chaos", "Heart of Chaos");
        add("item.woldsvaults.arcane_essence", "Arcane Essence");
        add("item.woldsvaults.arcane_shard", "Arcane Shard");
        add("item.the_vault.pog_prism", "Pog Prism");
        add("item.the_vault.chromatic_gold_nugget", "Chromatic Gold Nugget");
        add("item.the_vault.chromatic_gold_ingot", "Chromatic Gold Ingot");
        add("item.the_vault.smashed_vault_gem", "Smashed Vault Gem");
        add("item.the_vault.smashed_vault_gem_cluster", "Smashed Vault Gem Cluster");
        add("item.the_vault.wold_star_chunk", "Wold Star Chunk");
        add("item.the_vault.wold_star", "Wold Star");
        add("item.the_vault.gem_reagent_ashium", "Gem Reagent: Ashium");
        add("item.the_vault.gem_reagent_bomignite", "Gem Reagent: Bomignite");
        add("item.the_vault.gem_reagent_iskallium", "Gem Reagent: Woldium");
        add("item.the_vault.gem_reagent_xenium", "Gem Reagent: Xeenium");
        add("item.the_vault.gem_reagent_sparkletine", "Gem Reagent: Sparkletine");
        add("item.the_vault.gem_reagent_gorginite", "Gem Reagent: Gorginite");
        add("item.the_vault.gem_reagent_tubium", "Gem Reagent: Tubium");
        add("item.the_vault.gem_reagent_petzanite", "Gem Reagent: Petezanite");
        add("item.the_vault.gem_reagent_upaline", "Gem Reagent: Upaline");
        add("item.woldsvaults.idona_dagger", "Idonian Sacrificial Dagger");
        add("item.woldsvaults.velara_apple", "Velaran Emerald Apple");
        add("item.woldsvaults.wendarr_gem", "Wendarrian Focus Gem");
        add("item.woldsvaults.tome_of_tenos", "Tome of Tenos");
        add("block.the_vault.vault_palladium", "Vault Palladium");
        add("block.the_vault.vault_iridium", "Vault Iridium");
        add("block.woldsvaults.augment_crafting_table", "Augment Assembly Pedestal");
        add("item.woldsvaults.poltergeist_plum", "Poltergeist Plum");
        add("item.woldsvaults.crystal_seal_zealot", "Seal of the Zealot");
        add("item.woldsvaults.crystal_seal_warrior", "Seal of the Warrior");
        add("item.woldsvaults.eccentric_focus", "Eccentric Focus");
        add("item.woldsvaults.accoutre_focus", "Accoutre Focus");
        add("item.woldsvaults.xl_backpack", "Beeg Backpack");
        add("item.woldsvaults.community_token", "Community Token");
        add("item.woldsvaults.research_token", "Research Token");
        add("block.woldsvaults.xl_backpack", "Beeg Backpack");
        add("item.the_vault.trident", "Vault Trident");
        add("item.the_vault.battlestaff", "Vault Battlestaff");
        add("item.the_vault.map", "Vault Map");
        add("item.woldsvaults.layout_manipulator", "Etched Vault Layout");
        add("effect.woldsvaults.reaving", "Reaved");
        add("effect.woldsvaults.shrinking", "Shrinking");
        add("effect.woldsvaults.growing", "Growing");
        add("effect.woldsvaults.safer_space", "Safer Space");
        add("effect.woldsvaults.levitateii", "Levitate II");
        add("effect.woldsvaults.rerolled", "Reroll Cooldown");
        add("woldsvaults.key.cherish_item", "Cherish Item");
        add("key.woldsvaults.cherish_item", "Cherish Item");
        add("key.woldsvaults.open_wolds_vaults_config", "Open Wold's Vaults Config Screen");
        add("key.woldsvaults.is_feather_fixed", "Toggle Prismatic Feather Fix");
        add("key.category.woldsvaults", "Wold's Vaults");
        add("the_vault.gear_modification.reforge_weapon_type.description", "Reforges weapon type");
        add("the_vault.gear_modification.add_unusual_modifier.description", "Add unusual modifier");
        add("the_vault.gear_modification.add_unusual_modifier.no_modifiers", "No additional modifiers available");
        add("the_vault.gear_modification.add_unusual_modifier.full", "You cannot add more unusual modifiers to this gear piece");
        add("the_vault.gear_modification.unfreeze_all.description", "Unfreeze all Frozen modifiers");
        add("the_vault.gear_modification.unfreeze_all.no_modifiers", "There are no frozen modifiers to unfreeze");
        add("the_vault.gear_modification.freeze_all.description", "Freezes a legendary, corrupted, greater, or unusual modifier");
        add("the_vault.gear_modification.freeze_all.no_modifiers", "There are no modifiers to freeze");
        add("the_vault.gear_modification.freeze_all.frozen", "There is already a frozen modifier");
        add("create.item_attributes.has_unusual", "has an unusual modifier");
        add("create.item_attributes.has_unusual.inverted", "doesn't have an unusual modifier");
        add("create.item_attributes.has_divine", "is Divine");
        add("create.item_attributes.has_divine.inverted", "isn't Divine");
        add("create.item_attributes.unusual_prefix", "has an unusual \");%1$s\" prefix");
        add("create.item_attributes.unusual_prefix.inverted", "doesn't have an unusual \");%1$s\" prefix");
        add("create.item_attributes.unusual_suffix", "has an unusual \");%1$s\" suffix");
        add("create.item_attributes.unusual_suffix.inverted", "doesn't have an unusual \");%1$s\" suffix");
        add("create.item_attributes.offering_items", "is an Boss Rune with a Guaranteed \");%1$s\"");
        add("create.item_attributes.offering_items.inverted", "isn't an Boss Rune with a Guaranteed \");%1$s\"");
        add("create.item_attributes.offering_modifier", "has a \");%1$s\" Boss Rune modifier");
        add("create.item_attributes.offering_modifier.inverted", "doesn't have a \");%1$s\" Boss Rune modifier");
        add("create.item_attributes.targeted_mod_box_research", "is a Targeted Mod Box for the \");%1$s\" research");
        add("create.item_attributes.targeted_mod_box_research.inverted", "isn't a Targeted Mod Box for the \");%1$s\" research");
        add("create.item_attributes.antique_name", "is a \");%1$s\" Antique");
        add("create.item_attributes.antique_name.inverted", "isn't a \");%1$s\" Antique");
        add("create.item_attributes.rotten_offering", "is a rotten Boss Rune");
        add("create.item_attributes.rotten_offering.inverted", "isn't a rotten Boss Rune");
        add("create.item_attributes.etched_layout_type", "is an Etched Vault Layout with a \");%1$s\" layout");
        add("create.item_attributes.etched_layout_type.inverted", "isn't an Etched Vault Layout with a \");%1$s\" layout");
        add("create.item_attributes.etched_layout_tunnel", "is an Etched Vault Layout with a tunnel span of \");%1$s\"");
        add("create.item_attributes.etched_layout_tunnel.inverted", "isn't an Etched Vault Layout with a tunnel span of \");%1$s\"");
        add("create.item_attributes.etched_layout_value", "is an Etched Vault Layout with a value of \");%1$s\"");
        add("create.item_attributes.etched_layout_value.inverted", "isn't an Etched Vault Layout with a value of \");%1$s\"");
        add("create.item_attributes.gte_gate_pearl_size", "is a Gate Pearl with a size of \");%1$s\"");
        add("create.item_attributes.gte_gate_pearl_size.inverted", "is not a Gate Pearl with a size of \");%1$s\"");
        add("create.item_attributes.gte_gate_wave_count", "is a Gate Pearl with a wave count of at least \");%1$s\"");
        add("create.item_attributes.gte_gate_wave_count.inverted", "isn't a Gate Pearl with a wave count of at least \");%1$s\"");
        add("create.item_attributes.gte_gate_pearl_rewards", "is a Gate Pearl with a \");%1$s\" reward.");
        add("create.item_attributes.gte_gate_pearl_rewards.inverted", "isn't a Gate Pearl with a \");%1$s\" reward.");
        add("create.item_attributes.etching_set", "has a \");%1$s\" Etching");
        add("create.item_attributes.etching_set.inverted", "doesn't have a \");%1$s\" Etching");
        add("create.item_attributes.map_tier", "is a Vault Map with a tier of at least \");%1$s\"");
        add("create.item_attributes.map_tier.inverted", "isn't a Vault Map with a tier of at least \");%1$s\"");
        add("entity.the_vault.black_widow_boss", "Black Widow Boss");
        add("entity.the_vault.boogieman_boss", "Boogieman Boss");
        add("entity.the_vault.golem_boss", "Golem Boss");
        add("key.the_vault.quickselect.colossus", "Select and use ability: Colossus");
        add("woldsvaults.subtitle.saferspaces_proc", "Safer Spaces activated!");
        add("the_vault.gear_modification.tab.mythical", "Mythical");
        add("item.woldsvaults.pogominium_ingot", "POG-ominium Ingot");
        add("item.woldsvaults.infused_driftwood", "Infused Driftwood");
        add("item.woldsvaults.spark_of_inspiration", "Spark of Inspiration");
        add("block.woldsvaults.infused_driftwood_planks", "Infused Driftwood Planks");
        add("container.woldsvaults.infuser", "Vault Infuser");
        add("block.woldsvaults.chromatic_iron_vault_infuser", "Chromatic Iron Vault Infuser");
        add("block.woldsvaults.chromatic_steel_vault_infuser", "Chromatic Steel Vault Infuser");
        add("jei.category.woldsvaults.infuser", "Vault Infuser");
        add("item.woldsvaults.vault_diamond_nugget", "Vault Diamond Nugget");
        add("item.woldsvaults.chunk_of_power", "Chunk of Power");
        add("item.woldsvaults.soul_ichor", "Soul Ichor");
        add("item.woldsvaults.blazing_focus", "Blazing Focus");
        add("item.woldsvaults.suspension_focus", "Suspension Focus");
        add("block.woldsvaults.etching_shop_pedestal", "Etching Vendor Pedestal");
        add("block.woldsvaults.blacksmith_shop_pedestal", "Blacksmith Vendor Pedestal");
        add("block.woldsvaults.god_shop_pedestal", "God Vendor Pedestal");
        add("block.woldsvaults.rare_shop_pedestal", "Rare Vendor Pedestal");
        add("block.woldsvaults.omega_shop_pedestal", "Omega Vendor Pedestal");
        add("block.woldsvaults.spooky_shop_pedestal", "Spooky Vendor Pedestal");
        add("block.woldsvaults.gateway_channeling_block", "Gateway Channeling Beacon");
        add("item.woldsvaults.targeted_mod_box", "Targeted Mod Box");
        add("block.woldsvaults.mod_box_workstation", "Mod Box Workstation");
        add("item.woldsvaults.unidentified_gateway_pearl", "Unidentified Gateway Pearl");
        add("item.woldsvaults.prismatic_fiber", "Prismatic Fiber");
        add("block.woldsvaults.prismatic_fiber_block", "Block of Prismatic Fiber");
        add("block.woldsvaults.card_shop_pedestal", "Card Vendor Pedestal");
        add("block.woldsvaults.weaving_station", "Weaving Station");
        add("item.woldsvaults.recipe_blueprint", "Recipe Blueprint");
        add("item.woldsvaults.trinket_pouch", "Trinket Pouch");
        add("item.woldsvaults.chroma_core", "Chroma Core");
        add("item.woldsvaults.filter_necklace", "Filter Necklace");
        add("item.woldsvaults.crystal_seal_raid_rock_infinite_hard", "Brutal Raid Rock (Infinite)");
        add("item.the_vault.tool.material.nullite", "Nullite");
        add("block.the_vault.block_gem_wutodie_slab", "Wutodie Slab");
        add("block.the_vault.block_gem_wutodie_wall", "Wutodie Wall");
        add("block.the_vault.block_gem_wutodie_stairs", "Wutodie Stairs");
        add("item.woldsvaults.crystal_seal_alchemy", "Seal of the Alchemist");
    }
}
