package xyz.iwolfking.woldsvaults.datagen;

import com.simibubi.create.content.logistics.filter.ItemAttribute;
import iskallia.vault.VaultMod;
import iskallia.vault.config.MysteryEggConfig;
import iskallia.vault.util.StringUtils;
import net.minecraft.data.DataGenerator;
import net.minecraft.resources.ResourceLocation;
import net.minecraft.world.item.Item;
import net.minecraft.world.item.Items;
import net.minecraft.world.item.SpawnEggItem;
import net.minecraftforge.common.data.LanguageProvider;
import xyz.iwolfking.vhapi.api.registry.objective.CustomObjectiveRegistryEntry;
import xyz.iwolfking.woldsvaults.WoldsVaults;
import xyz.iwolfking.woldsvaults.api.core.vault_events.VaultEvent;
import xyz.iwolfking.woldsvaults.api.core.vault_events.VaultEventSystem;
import xyz.iwolfking.woldsvaults.init.*;
import xyz.iwolfking.woldsvaults.integration.arsnouveau.init.ArsSpawnEggItems;
import xyz.iwolfking.woldsvaults.integration.mekanism.init.ModGases;
import xyz.iwolfking.woldsvaults.integration.mekanism.init.ModPigments;
import xyz.iwolfking.woldsvaults.integration.vaultfilters.AlchemyIngredientTypeAttribute;
import xyz.iwolfking.woldsvaults.integration.vaultfilters.AlchemyItemAttribute;
import xyz.iwolfking.woldsvaults.integration.vaultfilters.CatalystItemAttribute;
import xyz.iwolfking.woldsvaults.integration.vaultfilters.VaultDollCompletedAttribute;
import xyz.iwolfking.woldsvaults.medallions.GreedMedallionTier;
import xyz.iwolfking.woldsvaults.objectives.data.EnchantedEventsRegistry;

import java.util.HashMap;
import java.util.LinkedHashMap;
import java.util.Map;

public class ModLanguageProvider extends LanguageProvider {

    private static final Map<String, String> LANG_REGISTRY = new HashMap<>();
    private static final Map<Item, String> ITEM_REGISTRY = new HashMap<>();

    public ModLanguageProvider(DataGenerator gen) {
        super(gen, WoldsVaults.MOD_ID, "en_us");
    }

    public static void register(String id, String text) {
        LANG_REGISTRY.put(id, text);
    }

    public static void register(Item item, String text) {
        ITEM_REGISTRY.put(item, text);
    }

    public void add(CustomObjectiveRegistryEntry entry, String text) {
        add("objective." + entry.getRegistryName().getNamespace() + "." + entry.getRegistryName().getPath(), text);
        add("objective." + VaultMod.MOD_ID + "." + entry.getRegistryName().getPath(), text);
    }

    public void add(ResourceLocation id, VaultEvent event) {
        add("vault_event." + id.getNamespace() + "." + id.getPath(), event.eventName);
        add("vault_event." + id.getNamespace() + "." + id.getPath() + "_description", event.eventDescription.getString());
        add("vault_event." + id.getNamespace() + "." + id.getPath() + "_message", event.eventMessage.getString());
    }

    public void add(ItemAttribute attribute, String text, String invertedText) {
        add("create.item_attributes." + attribute.getTranslationKey(), text);
        add("create.item_attributes." + attribute.getTranslationKey() + ".inverted", invertedText);
    }

    public void ritual(Item dummyItem, String ritualTooltip, ResourceLocation ritualId, String ritualName) {
        add("ritual." + ritualId.getNamespace() + "." + ritualId.getPath() + ".started", ritualName + " initiated!");
        add("ritual." + ritualId.getNamespace() + "." + ritualId.getPath() + ".finished", ritualName + " completed!");
        add(dummyItem, "Ritual: " + ritualName);
        add("item." + dummyItem.getRegistryName().getNamespace() + ".ritual_dummy." + dummyItem.getRegistryName().getPath().replace("ritual_dummy/", "") + ".tooltip", ritualTooltip);
    }

    public void pentacle(String pentacleId, String name, String introTitle, String intro, String usesTitle, String usesText) {
        add("book.occultism.dictionary_of_spirits.pentacles." + pentacleId + ".name", name);
        add("pentacle.occultism." + pentacleId, name);
        add("multiblock.occultism." + pentacleId, name);
        add("book.occultism.dictionary_of_spirits.pentacles." + pentacleId + ".intro.title", introTitle);
        add("book.occultism.dictionary_of_spirits.pentacles." + pentacleId + ".intro.text", intro);
        add("book.occultism.dictionary_of_spirits.pentacles." + pentacleId + ".uses.title", usesTitle);
        add("book.occultism.dictionary_of_spirits.pentacles." + pentacleId + ".uses.text", usesText);
    }


    @Override
    protected void addTranslations() {
        LANG_REGISTRY.forEach(this::add);
        ITEM_REGISTRY.forEach(this::add);
        iskallia.vault.init.ModConfigs.MYSTERY_EGG = new MysteryEggConfig().readConfig();
        iskallia.vault.init.ModConfigs.MYSTERY_EGG.POOL.forEach((productEntry, number) -> {
            if(productEntry.getItem() instanceof SpawnEggItem spawnEggItem && spawnEggItem != Items.PIG_SPAWN_EGG) {
                add("ritual." + WoldsVaults.MOD_ID + "." + "infuse_" + spawnEggItem.getType(productEntry.getNBT()).getRegistryName().getPath() + "_spawn_egg" + ".started", "Imbue Spawn Egg" + " initiated!");
                add("ritual." + WoldsVaults.MOD_ID + "." + "infuse_" + spawnEggItem.getType(productEntry.getNBT()).getRegistryName().getPath() + "_spawn_egg" + ".finished", "Imbue Spawn Egg" + " completed!");
            }
        });

        ModCustomVaultObjectiveEntries.getEntries().forEach(customObjectiveRegistryEntry -> {
            add(customObjectiveRegistryEntry, customObjectiveRegistryEntry.getName());
        });
        pentacle("velara", "Velara's Grove", "Velara's Grove", "**Purpose:** Commune with [#](00FF00)Velara[#]()\n\\\n\\\nPart of a quad divine alignment, [#](00FF00)Velara's Grove[#]() can be used to commune with the gracious Velara, who may provide the help of their green thumb with a suitable offering.\n", "Uses", "");
        pentacle("idona", "Idona's Battlefield", "Idona's Battlefield", "**Purpose:** Commune with [#](00FF00)Idona[#]()\n\\\n\\\nPart of a quad divine alignment, [#](00FF00)Idona's Battlefield[#]() can be used to commune with the ruthless Idona, who may lend their bloodthirsty nature to your rituals with a suitable offering.\n", "Uses", "");
        pentacle("tenos", "Tenos' Library", "Tenos' Library", "**Purpose:** Commune with [#](00FF00)Tenos[#]()\n\\\n\\\nPart of a quad divine alignment, [#](00FF00)Tenos' Library[#]() can be used to commune with the wise Tenos, who may lend their vast academic knowledge to your rituals with a suitable offering.\n", "Uses", "");
        pentacle("wendarr", "Wendarr's Study", "Wendarr's Study", "**Purpose:** Commune with [#](00FF00)Wendarr[#]()\n\\\n\\\nPart of a quad divine alignment, [#](00FF00)Wendarr's Study[#]() can be used to commune with the patient Wendarr, who may lend their time bending powers to your rituals with a suitable offering.\n", "Uses", "");
        pentacle("god_alignment", "Quaddeus Alignment", "Quaddeus Alignment", "**Purpose:** Commune with the [#](00FF00)Vault Gods[#]()\n\\\n\\\nThe full quad divine alignment, [#](00FF00)Quaddeus Alignment[#]() can be used to commune with all of the mighty Vault Gods at once, and with powerful enough offerings, may even assist with mighty rituals using their combined strength.\n", "Uses", "");

        add(new AlchemyItemAttribute(false), "is an Alchemy ingredient", "is not an Alchemy ingredient");
        add(new CatalystItemAttribute(false), "is an Alchemy catalyst", "is not an Alchemy catalyst");
        add(new AlchemyIngredientTypeAttribute(""), "is an Alchemy ingredient of type \"%1$s\"", "is not an Alchemy ingredient of type \"%1$s\"");
        add(ModBlocks.DECO_IDONA_ALTAR_BLOCK, "God Altar (Idona - Decorative)");
        add(ModBlocks.DECO_VELARA_ALTAR_BLOCK, "God Altar (Velara - Decorative)");
        add(ModBlocks.DECO_WENDARR_ALTAR_BLOCK, "God Altar (Wendarr - Decorative)");
        add(ModBlocks.DECO_TENOS_ALTAR_BLOCK, "God Altar (Tenos - Decorative)");
        add(ModBlocks.CONFIGURABLE_FLOATING_TEXT_BLOCK, "Magic Text");
        add(ModBlocks.OWNED_CRAFTING_TABLE_BLOCK, "Owned Crafting Table");
        add(ModBlocks.CRATE_CRACKER_BLOCK, "Crate Cracker");
        add(ModBlocks.SURVIVAL_OBJECTIVE_BLOCK, "Survival Pylon");
        add(ModItems.CRYSTAL_SEAL_SURVIVOR, "Seal of the Survivor");
        add(ModItems.SCAVENGER_POUCH_ITEM, "Scavenger Pouch");
        add(ModItems.COMBINED_TRINKET, "Fusion Trinket");
        add(ModItems.PRISMATIC_GLUE_BUCKET, "Bucket of Prismatic Glue");
        add(ModItems.MOLTEN_TRINKET_BUCKET, "Bucket of Molten Trinket");
        add(ModBlocks.PRISMATIC_GLUE_BLOCK, "Prismatic Glue");
        add(ModBlocks.MOLTEN_TRINKET_BLOCK, "Molten Trinket");
        add(ModItems.DUST_OF_POWER, "Dust of Power");
        add(ModItems.CONCEALED_CHAOS, "Concealed Chaos");
        add(ModEntities.LOGINAR, "Alien");
        add(ModEntities.ASTRAL_STALKER, "Astral Stalker");
        add(ModEntities.NEBULA_SENTINEL, "Nebula Sentinel");
        add(ModEntities.STAR_DEVOURER_ENTITY, "Star Beast");
        add(ModEntities.SINGULARITY_CREEPER, "Singularity Creeper");
        add(ModEntities.CUSTOM_FANGS, "Fangs");
        add(iskallia.vault.init.ModEntities.NECROMANCY_SKELETON, "Skeleton Minion");
        add(iskallia.vault.init.ModEntities.NECROMANCY_GOLEM, "Golem Minion");
        add(iskallia.vault.init.ModEntities.NECROMANCY_BOLT, "Necromancy Bolt");
        add(ModItems.GREED_TREE_RESET_ITEM, "Greed Infused Neuralizer");
        add(ModItems.BLUE_VAULT_ESSENCE, "Blue Vault Essence");
        add(ModItems.GREEN_VAULT_ESSENCE, "Green Vault Essence");
        add(ModItems.YELLOW_VAULT_ESSENCE, "Yellow Vault Essence");
        add(ModItems.GREED_MEDALLIONS.get(GreedMedallionTier.SCAVENGER_1), "Scavenger 1 Medallion");
        add(ModItems.GREED_MEDALLIONS.get(GreedMedallionTier.SCAVENGER_2), "Scavenger 2 Medallion");
        add(ModItems.GREED_MEDALLIONS.get(GreedMedallionTier.SCAVENGER_3), "Scavenger 3 Medallion");
        add(ModItems.GREED_MEDALLIONS.get(GreedMedallionTier.LOOTER_1), "Looter 1 Medallion");
        add(ModItems.GREED_MEDALLIONS.get(GreedMedallionTier.LOOTER_2), "Looter 2 Medallion");
        add(ModItems.GREED_MEDALLIONS.get(GreedMedallionTier.LOOTER_3), "Looter 3 Medallion");
        add(ModItems.GREED_MEDALLIONS.get(GreedMedallionTier.HUNTER_1), "Hunter 1 Medallion");
        add(ModItems.GREED_MEDALLIONS.get(GreedMedallionTier.HUNTER_2), "Hunter 2 Medallion");
        add(ModItems.GREED_MEDALLIONS.get(GreedMedallionTier.HUNTER_3), "Hunter 3 Medallion");
        add(ModItems.GREED_MEDALLIONS.get(GreedMedallionTier.MASTER_1), "Master 1 Medallion");
        add(ModItems.GREED_MEDALLIONS.get(GreedMedallionTier.MASTER_2), "Master 2 Medallion");
        add(ModItems.GREED_MEDALLIONS.get(GreedMedallionTier.MASTER_3), "Master 3 Medallion");
        add(ModItems.GREED_MEDALLIONS.get(GreedMedallionTier.CHAMPION_1), "Champion 1 Medallion");
        add(ModItems.GREED_MEDALLIONS.get(GreedMedallionTier.CHAMPION_2), "Champion 2 Medallion");
        add(ModItems.GREED_MEDALLIONS.get(GreedMedallionTier.CHAMPION_3), "Champion 3 Medallion");
        add(ModItems.GREED_MEDALLIONS.get(GreedMedallionTier.LEGEND), "Legend Medallion");
        add("item.woldsvaults.unidentified_ancient_unique", "Unidentified Ancient Unique");
        add(ModPigments.IDONA_RED.getTranslationKey(), "Idona Red Pigment");
        add(ModPigments.WENDARR_YELLOW.getTranslationKey(), "Wendarr Yellow Pigment");
        add(ModPigments.VELARA_GREEN.getTranslationKey(), "Velara Green Pigment");
        add(ModPigments.TENOS_BLUE.getTranslationKey(), "Tenos Blue Pigment");
        add(ModPigments.FOIL_PIGMENT.getTranslationKey(), "Card Foil Coating");
        add(ModPigments.CARD_PAINT_BASE.getTranslationKey(), "Card Paint Base");
        add(ModPigments.CARD_PAINT_BLUE.getTranslationKey(), "Blue Card Paint");
        add(ModPigments.CARD_PAINT_GREEN.getTranslationKey(), "Green Card Paint");
        add(ModPigments.CARD_PAINT_RED.getTranslationKey(), "Red Card Paint");
        add(ModPigments.CARD_PAINT_YELLOW.getTranslationKey(), "Yellow Card Paint");
        add(ModGases.LEAD_GAS.getTranslationKey(), "Gaseous Lead");
        add(ModItems.LEAD_DYE_BASE, "Lead Dye Base");
        add("fix.woldsvaults.schematic_terminal_no_permission", "You do not have permission to place an Overworld Inscription here!");
        add("fluid.woldsvaults.molten_trinket", "Molten Trinket");
        add("block.woldsvaults.prismatic_glue", "Prismatic Glue");
        add("block.woldsvaults.flowing_prismatic_glue", "Flowing Prismatic Glue");
        add("tile.woldsvaults.trinket_fusion_forge", "Trinket Fusion Forge");
        add(ModBlocks.TRINKET_FUSION_BLOCK, "Trinket Fusion Forge");
        add(ModEffects.BURN, "Burning");
        add(ModEffects.BLITZ, "Blitz");
        add(ModEffects.ARMORED, "Armored");
        add(ModEffects.STEADFAST, "Steadfast");
        add("message.woldsvaults.filled_bottle_alchemy_archive", "You have all effects unlocked! Your %1$s has been refilled!");
        add("message.woldsvaults.god_level_up", "Your alignment with %1$s has reached level %2$s.");
        add("message.woldsvaults.stirrings_dormant", "The gods are silent.");
        add("message.woldsvaults.ultimate_locked", "Your god has not yet granted this power.");
        add("message.woldsvaults.eyes_of_god_outside_vault", "Eyes of God only sees inside a vault.");
        add("message.woldsvaults.eyes_of_god_revealed", "Revealed %s rooms.");
        add("command.woldsvaults.prevent_back_into_vault", "You cannot return into The Vault!");
        add("woldsvaults.special.fruit_rotting", "§4You feel the Vault start to rot away...");
        add("woldsvaults.special.rotten", "§4The Vault has rotted!");
        add("config.waila.plugin_miningspeedometer.speedometer", "Enable Speedometer Tooltip");
        add("vaultobjectiveblocks.jade.tooltip.brewing_altar", "%1$s brews remaining");
        add("vaultobjectiveblocks.jade.tooltip.rune_boss_pillar", "%1$s runes inserted");
        add("speedometer.jade.tooltip.instamine", "Instaminable ✔");
        add("speedometer.jade.tooltip.speed_needed", "+%s Mining Speed to Instamine %s");
        add("speedometer.jade.tooltip.speed_additional", "+%s more Mining Speed to Instamine %s");
        add("speedometer.jade.tooltip.speed_for_breakpoint", "+%1$s more Mining Speed to break in %2$s ticks");
        add("config.waila.plugin_woldsvaults.jade_plugin", "Wold's Plugins");
        add("deck.woldsvaults.nitwit_modifier", "increased card efficiency inside Arcane slots (Arcane slots may only have non-Arcane slots inserted)");
        add("deck.woldsvaults.void_modifier", "increased card efficiency per empty card slot");
        add("deck.woldsvaults.adjacency_modifier", "increased card efficiency %2$s %1$s card");
        add("deck.woldsvaults.adjacency_modifier_type_1", "per %1$s");
        add("deck.woldsvaults.adjacency_modifier_type_2", "when %1$s to at least one");
        add("deck.woldsvaults.adjacency_type_orthogonal", "orthogonal");
        add("deck.woldsvaults.adjacency_type_diagonal", "diagonal");
        add("deck.woldsvaults.adjacency_type_surrounding", "surrounding");
        add("deck.woldsvaults.adjacency_type_surrounding_2", "within 2 spaces");
        add("deck.woldsvaults.adjacency_type_starcross", "within two orthogonal or one diagonal");
        add("deck.woldsvaults.adjacency_type_row", "row");
        add("deck.woldsvaults.adjacency_type_column", "column");
        add("deck.woldsvaults.adjacency_type_adjacent", "adjacent");
        add("deck.woldsvaults.adjacency_type_above", "above");
        add("deck.woldsvaults.adjacency_type_below", "below");
        add("deck.woldsvaults.adjacency_type_left", "left");
        add("deck.woldsvaults.adjacency_type_right", "right");
        add("deck.woldsvaults.adjacency_type_failure", "invalid configuration");
        add("deck.woldsvaults.dominance_deck_modifier_current", "Currently: %1$s");
        add("deck.woldsvaults.dominance_deck_modifier_dominant", "+%1$s card efficiency to cards with the most dominant group in the deck (%2$s)");
        add("deck.woldsvaults.dominance_deck_modifier_minority", "+%1$s card efficiency to cards with the least dominant group in the deck (%2$s)");
        add("deck.woldsvaults.dominance_deck_modifier_exclusion", "Excludes %1$s group");
        add("deck.woldsvaults.group_synergy_modifier", "card efficiency for %2$s cards %3$s %1$s cards in your deck");
        add("command.woldsvaults.give_loot", "Given a %1$s");
        add("rewards.woldsvaults.unclaimed_rewards", "You have unclaimed rewards to collect! Do §6/timetrial rewards§r to claim!");
        add("vault_event.woldsvaults.swap_task", "You have been swapped with %1$s.");
        add("vault_event.woldsvaults.legacy_event_message", "%1$s encountered a %2$s Event!");
        add("vault_event.woldsvaults.event_cascade", "%1$s %2$s Event has cascaded onto you!");
        add("vault_event.woldsvaults.tombstone_elite", "An undead Elite has arisen!");
        add("vault_event.woldsvaults.tombstone_wither", "You feel your body start to decay...");
        add("vault_event.woldsvaults.tombstone_weaken", "Your muscles grow tense!");
        add("vault_event.woldsvaults.tombstone_explode", "The grave was rigged to explode!");
        add("vault_event.woldsvaults.tombstone_soul_shard_increase", "You feel the Soul Shard drop rate increase.");
        add("vault_event.woldsvaults.tombstone_haunted", "The Vault feels a bit more haunted now...");
        add("vault_event.woldsvaults.tombstone_ethereal", "A wave of phantasmal energy echoes throughout the vault.");
        add("vault_event.woldsvaults.tombstone_spirits", "A wave of ghosts assaults you!");
        add("vault_event.woldsvaults.tombstone_zombie", "A zombie is unearthed!");
        add("vault_event.woldsvaults.tombstone_skeleton", "Skeletons are unearthed!");
        add("vault_event.woldsvaults.tombstone_horse", "A horse is unearthed?!");
        add("vault_event.woldsvaults.cockroach_celebrate", "The dancing cockroaches are fond towards you and bless each player with 3 random positive events!");
        add("vault_event.woldsvaults.cockroach_hate", "The dancing cockroaches hate your guts and curse everyone in the vault with 3 random negative events!");
        add("misc.woldsvaults.flight_block_0", "You cannot fly inside the Vault!");
        add("vault_objective.woldsvaults.time_trial_player_best", "%1$s just finished a §d%2$s§r vault with a new best time of §6%3$s§r (previously: §6%4$s§r)");
        add("vault_objective.woldsvaults.time_trial_new_competition_best", "%1$s just beat the §6Weekly Time Trial§r best of §6%2$s§r with a time of §6%3$s§r");
        add("vault_objective.woldsvaults.time_trial_new_competition_first", "%1$s just set the first §6Weekly Time Trial§r entry to beat with a time of §6%2$s§r!");
        add("vault_objective.woldsvaults.survival_completion", "You are now able to leave the vault at any time to complete or continue surviving to accumulate rewards.");
        add("vault_objective.woldsvaults.corrupted_exit", "Find an escape.");
        add("vault_objective.woldsvaults.corrupted_shatter", "You sense a portal shattering");
        add("vault_objective.woldsvaults.corrupted_complete", "Vault Completed!");
        add("vault_objective.woldsvaults.corrupted_fruit_disable", "Seems pointless...");
        add("vault_objective.woldsvaults.survival_fruit_disable", "A mysterious force prevents you from eating the fruit.");
        add("vault_objective.woldsvaults.survival_wave_increment", "§4Survival Wave Tier increased!");
        add("unlock_goal.woldsvaults.idona_theme", "Idona shares insight on entering their domain with you.");
        add("unlock_goal.woldsvaults.velara_theme", "Velara shares insight on entering their domain with you.");
        add("unlock_goal.woldsvaults.wendarr_theme", "Wendarr shares insight on entering their domain with you.");
        add("unlock_goal.woldsvaults.tenos_theme", "Tenos shares insight on entering their domain with you.");
        add("unlock_goal.woldsvaults.wizard_trinket_pouch", "Your arcane energy has enlightened you!");
        add("unlock_goal.woldsvaults.looters_trinket_pouch", "You are enlightened with a beautiful dream of boundless loot!");
        add("unlock_goal.woldsvaults.treasure_jewel", "You envision a better way of opening Treasure Chests!");
        add("unlock_goal.woldsvaults.underwater_theme", "You ponder the thought of an entire vault under the sea...");
        add("vault_gear_modifiers.woldsvaults.safer_spaces_recharging_barrier", "Recharging Barrier");
        add("vault_gear_modifiers.woldsvaults.safer_spaces_improved_block", "Improved Block");
        add("key.woldsvaults.open_inventory_hud", "Open Inventory HUD Edit Screen");
        add("util.woldsvaults.objective_text", "Objective: ");
        add("util.woldsvaults.vault_modifier_added", "%1$s was added to the Vault!");
        add("util.woldsvaults.timed_modifier_added", "%1$s added %2$s to the Vault for %3$s seconds!");
        add("item.woldsvaults.core_of_the_vault_gods", "Core of the Vault Gods");
        add("item.woldsvaults.gods_mastery", "God's Mastery");
        add("item.woldsvaults.greedy_ticket", "Greedy Ticket");
        add("item.woldsvaults.rotten_heart", "Rotten Heart");
        add("item.woldsvaults.rotten_apple", "Rotten Apple");
        add("item.woldsvaults.verdant_globule", "Verdant Globule");
        add("item.woldsvaults.erratic_ember", "Erratic Ember");
        add("item.woldsvaults.refined_powder", "Refined Powder");
        add("item.woldsvaults.auric_crystal", "Auric Crystal");
        add("curios.identifier.shard_pouch", "Shard Pouch");
        add("curios.identifier.trinket_pouch", "Trinket Pouch");
        add("item.woldsvaults.trinket_pouch_stored_trinkets", "Stored Trinkets: ");
        add("curios.identifier.green_trinket", "Green Trinket");
        add("curios.modifiers.trinket_pouch", "Pouch Modifiers");
        add("ftbquests.task.woldsvaults.vault_level", "Vault Level");
        add("ftbquests.task.woldsvaults.enter_vault", "Enter Vault");
        add("ftbquests.task.woldsvaults.complete_bounty", "Complete Bounty");
        add("item.scannable.vault_ores_module", "Scanner Module: Vault Ores");
        add("item.scannable.vault_chests_module", "Scanner Module: All Chests");
        add("item.scannable.vault_chests_module_living", "Scanner Module: Living Chests");
        add("item.scannable.vault_chests_module_gilded", "Scanner Module: Gilded Chests");
        add("item.scannable.vault_chests_module_ornate", "Scanner Module: Ornate Chests");
        add("item.scannable.vault_chests_module_raw", "Scanner Module: Raw Chests");
        add("item.scannable.vault_chests_module_wooden", "Scanner Module: Wooden Chests");
        add("item.scannable.vault_chests_module_treasure", "Scanner Module: Treasure Chests");
        add("item.scannable.vault_coins_module", "Scanner Module: Coin Stacks");
        add("item.scannable.vault_doors_module", "Scanner Module: Vault Doors");
        add("item.scannable.vault_objectives_module", "Scanner Module: Vault Objectives");
        add("item.scannable.vault_spirit_module", "Scanner Module: Vault Spirits");
        add("item.scannable.vault_cake_module", "Scanner Module: Vault Cakes");
        add("item.scannable.vault_treasure_doors_module", "Scanner Module: Treasure Doors");
        add("item.scannable.vault_dungeon_doors_module", "Scanner Module: Dungeon Doors");
        add("item.scannable.vault_vendoors_module", "Scanner Module: Vendoors");
        add("item.scannable.vault_pylon_module", "Scanner Module: Pylons");
        add(ModItems.CRYSTAL_SEAL_UNHINGED, "Seal of the Psychopath");
        add(ModItems.CRYSTAL_SEAL_DOOMSAYER, "Seal of the Doomsayer");
        add(ModItems.CRYSTAL_SEAL_DOOMSAYER_SHUFFLE, "Seal of the Shuffling Doomsayer");
        add(ModItems.CRYSTAL_SEAL_SPIRITS, "Seal of the Exorcist");
        add(ModItems.CRYSTAL_SEAL_ENCHANTER, "Seal of the Enchanter");
        add(ModItems.CRYSTAL_SEAL_TITAN, "Seal of the Titan");
        add(ModItems.UNINFUSED_TERRASTEEL_INGOT, "Uninfused Terrasteel Ingot");
        add(ModItems.POGGING_SEED_BASE, "Pogging Seed Base");
        add(ModItems.ECHOING_SEED_BASE, "Echoing Seed Base");
        add(ModItems.MOB_BINDING_STONE, "Mob Binding Stone");
        add(ModItems.CRYSTAL_SEAL_UNHINGED_SCAVINGO, "Seal of the Senseless Scavingo");
        add("tooltip.woldsvaults.egg_supported", "§a✔ §7Supported");
        add("tooltip.woldsvaults.egg_unsupported", "§c✘ §7Unsupported");
        add("menu.woldsvaults.rewards_menu", "Rewards Menu");
        add("item.the_vault.plushie", "Vault Plushie");
        add("item.the_vault.loot_sack", "Vault Sack");
        add("item.the_vault.rang", "Vaultarang");
        add("item.woldsvaults.weapon_augmenter", "Weapon Augmenter");
        add("item.woldsvaults.greedy_vault_rock", "Greedy Vault Rock");
        add("jei.the_vault.survival_gear_cache_loot", "Survival Gear Cache");
        add("jei.the_vault.wooden_dungeon_barrel_loot", "Wooden Dungeon Barrel");
        add("jei.the_vault.time_trial_reward_crate_loot", "Time Trial Reward Crate");
        add("jei.the_vault.completion_crate_unhinged_scavenger_loot", "Unhinged Scavenger Crate");
        add("jei.the_vault.completion_crate_haunted_braziers_loot", "Haunted Braziers Crate");
        add("jei.the_vault.completion_crate_enchanted_elixir_loot", "Enchanted Elixir Crate");
        add("jei.the_vault.completion_crate_zealot_loot", "Zealot Crate");
        add("jei.the_vault.completion_crate_bingo_wold_loot", "Bingo Crate");
        add("jei.the_vault.completion_crate_ballistic_bingo_loot", "Ballistic Bingo Crate");
        add("jei.the_vault.completion_crate_ballistic_bingo_full_loot", "Ballistic Bingo Crate (Full)");
        add("jei.the_vault.completion_crate_bingo_wold_full_loot", "Bingo Crate (Full)");
        add("jei.the_vault.completion_crate_brutal_bosses_loot", "Brutal Bosses Crate");
        add("jei.the_vault.completion_crate_hyper_loot", "Hyper Crate");
        add("jei.the_vault.completion_crate_corrupted_loot", "Corrupted Crate");
        add("jei.the_vault.completion_crate_chaos_loot", "Chaos Completion Crate");
        add("jei.the_vault.dungeon_mobs_loot", "Dungeon Mobs");
        add("jei.the_vault.dungeon_boss_loot", "Dungeon Boss");
        add("jei.the_vault.enigma_chest_map_loot", "Enigma Chest (Map)");
        add("jei.the_vault.gilded_chest_map_loot", "Gilded Chest (Map)");
        add("jei.the_vault.living_chest_map_loot", "Living Chest (Map)");
        add("jei.the_vault.ornate_chest_map_loot", "Ornate Chest (Map)");
        add("jei.the_vault.wooden_chest_map_loot", "Wooden Chest (Map)");
        add("jei.the_vault.treasure_chest_map_loot", "Treasure Chest (Map)");
        add("jei.the_vault.treasure_pedestal_map_loot", "Treasure Pedestal (Map)");
        add("jei.the_vault.gilded_barrel_loot", "Gilded Barrel");
        add("jei.the_vault.ornate_barrel_loot", "Ornate Barrel");
        add("jei.the_vault.living_barrel_loot", "Living Barrel");
        add("jei.the_vault.digsite_sand_loot", "Digsite Sand");
        add("jei.the_vault.iskallian_leaves_loot", "Woldian Leaves");
        add("jei.the_vault.hellish_sand_loot", "Hellish Sand");
        add("jei.the_vault.vendor_pedestal_loot", "Vendor Pedestal");
        add("jei.the_vault.dungeon_pedestal_loot", "Dungeon Pedestal");
        add("jei.the_vault.treasure_pedestal_loot", "Treasure Pedestal");
        add("jei.the_vault.brazier_pillage_loot", "Brazier Pillaging");
        add("jei.the_vault.tombstone_loot", "Tombstone");
        add("jei.the_vault.god_altar_wendarr_loot", "God Altar (Wendarr)");
        add("jei.the_vault.god_altar_idona_loot", "God Altar (Idona)");
        add("jei.the_vault.god_altar_tenos_loot", "God Altar (Tenos)");
        add("jei.the_vault.god_altar_velara_loot", "God Altar (Velara)");
        add("jei.woldsvaults.trinket_fusion", "Trinket Fusion Forge");
        add("item.the_vault.gem_iskallium", "§5Woldium Gem");
        add("item.the_vault.key_iskallium", "§5Woldium Key");
        add("item.the_vault.cluster_iskallium", "§5Woldium Cluster");
        add("item.the_vault.chunk_iskallium", "§5Woldium Chunk");
        add("block.the_vault.ore_iskallium", "§5Woldium Ore");
        add("block.the_vault.ore_iskallium_stone", "§5Woldium Ore - Stone");
        add("block.the_vault.ore_iskallium_vault_stone", "§5Woldium Ore - Vault Stone");
        add("block.the_vault.ore_iskallium_white", "§5Woldium Ore - Diorite");
        add("block.the_vault.treasure_door_iskallium", "§5Woldium Treasure Door");
        add("item.the_vault.tool.ravager", "Ravager");
        add("item.the_vault.tool.raker", "Raker");
        add("item.the_vault.tool.none", "Stick");
        add(ModBlocks.VAULT_SALVAGER_BLOCK, "Vault Salvager");
        add(ModBlocks.WUTODIE, "Block of Wutodie Gem");
        add("block.woldsvaults.dungeon_pedestal", "Dungeon Pedestal");
        add("block.woldsvaults.iskallian_leaves", "Woldian Leaves");
        add("block.woldsvaults.hellish_sand", "Hellish Sand");
        add("block.woldsvaults.brewing_altar", "Brewing Altar");
        add("block.the_vault.dungeon_door", "Dungeon Door");
        add("block.the_vault.treasure_door", "Treasure Door");
        add("block.the_vault.cake", "Cake");
        add(ModItems.GEM_BOX, "Gem Box");
        add(ModItems.SUPPLY_BOX, "Supply Box");
        add(ModItems.AUGMENT_BOX, "Augment Box");
        add(ModItems.INSCRIPTION_BOX, "Inscription Box");
        add(ModItems.OMEGA_BOX, "Omega Box");
        add(ModItems.CATALYST_BOX, "Catalyst Box");
        add(ModItems.ENIGMA_EGG, "Enigma Egg");
        add(ArsSpawnEggItems.DRYGMY_SPAWN_EGG, "Drygmy Spawn Egg");
        add("itemGroup.woldsvaults", "Wold's Vaults");
        add("item.woldsvaults.zephyr_charm", "Zephyr Charm");
        add("item.woldsvaults.augment_piece", "Augment Piece");
        add("item.the_vault.scavenger_benitoite_gemstone", "Benitoite Gemstone");
        add("item.the_vault.scavenger_wutodic_gemstone", "Wutodic Gemstone");
        add("item.the_vault.scavenger_echoing_gemstone", "Echoing Gemstone");
        add("item.the_vault.scavenger_pogging_gemstone", "Pogging Gemstone");
        add("item.the_vault.scavenger_ender_heart", "Enderman Heart");
        add("item.the_vault.scavenger_enderman_eye", "Enderman Eye");
        add("item.the_vault.scavenger_ender_crystal", "Ender Crystal");
        add("item.the_vault.scavenger_ender_artifact", "Ender Artifact");
        add(ModItems.ALTAR_DECATALYZER, "Altar Recatalyzer");
        add("item.woldsvaults.expertise_orb", "Expertise Orb");
        add("item.woldsvaults.skill_orb", "Skill Orb");
        add("item.woldsvaults.chromatic_iron_angel_ring", "Chromatic Iron Angel Ring");
        add("item.woldsvaults.chromatic_gold_angel_ring", "Chromatic Gold Angel Ring");
        add("item.woldsvaults.chromatic_steel_angel_ring", "Chromatic Steel Angel Ring");
        add("item.woldsvaults.black_chromatic_steel_angel_ring", "Black Chromatic Steel Angel Ring");
        add("item.woldsvaults.prismatic_angel_ring", "Prismatic Angel Ring");
        add("item.woldsvaults.crystal_seal_corrupt", "Seal of the Unknown");
        add("item.woldsvaults.ruined_essence", "Ruined Essence");
        add("item.woldsvaults.nullite_fragment", "Nullite Fragment");
        add("item.woldsvaults.nullite_crystal", "Nullite Crystal");
        add("item.woldsvaults.obelisk_resonator", "Obelisk Resonator");
        add("block.woldsvaults.scavenger_altar", "Deco Scavenger Altar");
        add("block.woldsvaults.obelisk", "Deco Obelisk");
        add("block.woldsvaults.lodestone", "Deco Lodestone");
        add("block.woldsvaults.monolith", "Deco Brazier");
        add("block.woldsvaults.mob_barrier_red", "Mob Barrier");
        add("block.woldsvaults.fractured_obelisk", "Fractured Obelisk");
        add("block.woldsvaults.monolith_controller", "Monolith Controller");
        add("block.woldsvaults.nullite_ore", "Nullite Ore");
        add("block.woldsvaults.doll_dismantler", "Doll Blender");
        add("block.woldsvaults.tombstone", "Tombstone");
        add(ModEntities.WOLD, "Wold");
        add("entity.woldsvaults.green_ghost", "Toxic Ghost");
        add("entity.woldsvaults.black_ghost", "Unholy Ghost");
        add("entity.woldsvaults.blue_ghost", "Chilly Ghost");
        add("entity.woldsvaults.brown_ghost", "Cursed Ghost");
        add("entity.woldsvaults.dark_blue_ghost", "Arcane Ghost");
        add("entity.woldsvaults.dark_gray_ghost", "Steel Ghost");
        add("entity.woldsvaults.dark_red_ghost", "Crimson Ghost");
        add("entity.woldsvaults.purple_ghost", "Enchanted Ghost");
        add("entity.woldsvaults.red_ghost", "Red Ghost");
        add("entity.woldsvaults.yellow_ghost", "Rapid Ghost");
        add("entity.woldsvaults.hostile_turkey", "Aggressive Turkey");
        add("entity.woldsvaults.hostile_chicken", "Aggressive Chicken");
        add("entity.woldsvaults.hostile_sheep", "Aggressive Sheep");
        add("entity.woldsvaults.hostile_pig", "Aggressive Pig");
        add("entity.woldsvaults.cranberry_slime", "Cranberry Sauce Slime");
        add("entity.woldsvaults.haturkin", "Haturkin");
        add("entity.woldsvaults.magic_missile", "Magic Missile");
        add("death.attack.woldsvaults.magic_missile", "%1$s was blown apart by %2$s's Magic Missile");
        add("item.woldsvaults.wold_spawn_egg", "Wold Spawn Egg");
        add("item.woldsvaults.boogieman_spawn_egg", "Boogieman Spawn Egg");
        add("item.woldsvaults.monster_eye_spawn_egg", "Monster Eye Spawn Egg");
        add("item.woldsvaults.robot_spawn_egg", "Robot Spawn Egg");
        add("item.woldsvaults.blue_blaze_spawn_egg", "Blue Blaze Spawn Egg");
        add("item.woldsvaults.capstone_frenzy", "Frenzy Capstone");
        add("item.woldsvaults.capstone_prosperous", "Prosperous Capstone");
        add("item.woldsvaults.capstone_all_seeing_eye", "All Seeing Eye Capstone");
        add("item.woldsvaults.capstone_vendoors", "Vendoors Capstone");
        add("item.woldsvaults.capstone_enchanted", "Enchanted Capstone");
        add("item.woldsvaults.waxing_augmenter", "Waxing Augmenter");
        add("item.woldsvaults.waning_augmenter", "Waning Augmenter");
        add("item.woldsvaults.repair_augmenter", "Repair Augmenter");
        add("item.woldsvaults.crystal_reinforcement", "Prismatic Reinforcement");
        add("item.woldsvaults.resonating_reinforcement", "Resonating Reinforcement");
        add("item.woldsvaults.stylish_focus", "Stylish Focus");
        add("item.woldsvaults.chiseling_focus", "Chiseling Focus");
        add("item.woldsvaults.vault_rock_candy", "Vault Rock Candy");
        add("item.woldsvaults.hasty_pomegranate", "Hasty Pomegranate");
        add("item.woldsvaults.wisdom_fruit", "Wisdom Fruit");
        add("item.woldsvaults.uber_chaos_catalyst", "Unhinged Vault Rock");
        add("item.woldsvaults.vaultar_box", "Vaultar Box");
        add("item.woldsvaults.mercy_orb", "Merciful Orb");
        add("item.woldsvaults.general_decor_scroll", "Vault Deco Scroll");
        add("item.woldsvaults.extraordinary_pog_prism", "Extraordinary Pog Prism");
        add("item.woldsvaults.heart_of_chaos", "Heart of Chaos");
        add("item.woldsvaults.arcane_essence", "Arcane Essence");
        add("item.woldsvaults.arcane_shard", "Arcane Shard");
        add(ModItems.POG_PRISM, "Pog Prism");
        add(ModItems.CHROMATIC_GOLD_NUGGET, "Chromatic Gold Nugget");
        add(ModItems.CHROMATIC_GOLD_INGOT, "Chromatic Gold Ingot");
        add(ModItems.SMASHED_VAULT_GEM, "Smashed Vault Gem");
        add(ModItems.SMASHED_VAULT_GEM_CLUSTER, "Smashed Vault Gem Cluster");
        add(ModItems.WOLD_STAR_CHUNK, "Wold Star Chunk");
        add(ModItems.WOLD_STAR, "Wold Star");
        add(ModItems.GEM_REAGENT_ASHIUM, "Gem Reagent: Ashium");
        add(ModItems.GEM_REAGENT_BOMIGNITE, "Gem Reagent: Bomignite");
        add(ModItems.GEM_REAGENT_ISKALLIUM, "Gem Reagent: Woldium");
        add(ModItems.GEM_REAGENT_XENIUM, "Gem Reagent: Xeenium");
        add(ModItems.GEM_REAGENT_SPARKLETINE, "Gem Reagent: Sparkletine");
        add(ModItems.GEM_REAGENT_GORGINITE, "Gem Reagent: Gorginite");
        add(ModItems.GEM_REAGENT_TUBIUM, "Gem Reagent: Tubium");
        add(ModItems.GEM_REAGENT_PETEZANITE, "Gem Reagent: Petezanite");
        add(ModItems.GEM_REAGENT_UPALINE, "Gem Reagent: Upaline");
        add("item.woldsvaults.idona_dagger", "Idonian Sacrificial Dagger");
        add("item.woldsvaults.velara_apple", "Velaran Emerald Apple");
        add("item.woldsvaults.wendarr_gem", "Wendarrian Focus Gem");
        add("item.woldsvaults.tome_of_tenos", "Tome of Tenos");
        add(ModBlocks.VAULT_PALLADIUM, "Vault Palladium");
        add(ModBlocks.VAULT_IRIDIUM, "Vault Iridium");
        add("block.woldsvaults.augment_crafting_table", "Augment Assembly Pedestal");
        add("item.woldsvaults.poltergeist_plum", "Poltergeist Plum");
        add("item.woldsvaults.crystal_seal_zealot", "Seal of the Zealot");
        add("item.woldsvaults.crystal_seal_warrior", "Seal of the Warrior");
        add("item.woldsvaults.eccentric_focus", "Eccentric Focus");
        add("item.woldsvaults.accoutre_focus", "Accoutre Focus");
        add("item.woldsvaults.xl_backpack", "Beeg Backpack");
        add("item.woldsvaults.community_token", "Community Token");
        add("item.woldsvaults.research_token", "Research Token");
        add("block.woldsvaults.xl_backpack", "Beeg Backpack");
        add("item.the_vault.trident", "Vault Trident");
        add("item.the_vault.battlestaff", "Vault Battlestaff");
        add("item.the_vault.map", "Vault Map");
        add("item.woldsvaults.layout_manipulator", "Etched Vault Layout");
        add("effect.woldsvaults.reaving", "Reaved");
        add("effect.woldsvaults.echoing", "Echoing");
        add("effect.woldsvaults.shrinking", "Shrinking");
        add("effect.woldsvaults.growing", "Growing");
        add("effect.woldsvaults.safer_space", "Safer Space");
        add("effect.woldsvaults.levitateii", "Levitate II");
        add("effect.woldsvaults.rerolled", "Reroll Cooldown");
        add("effect.the_vault.glacial_shatter", "Glacial Shatter");
        add(ModEffects.EMPOWER, "Empower");
        add(ModEffects.QUICKENING, "Quickening");
        add("woldsvaults.key.cherish_item", "Cherish Item");
        add("key.woldsvaults.cherish_item", "Cherish Item");
        add("key.woldsvaults.open_wolds_vaults_config", "Open Wold's Vaults Config Screen");
        add("key.woldsvaults.toggle_better_combat", "Toggle Better Combat");
        add("key.woldsvaults.is_feather_fixed", "Toggle Prismatic Feather Fix");
        add("key.woldsvaults.configure_trinket", "Configure Hovered Trinket");
        add("key.category.woldsvaults", "Wold's Vaults");
        add("the_vault.gear_modification.reforge_weapon_type.description", "Reforges weapon type");
        add("the_vault.gear_modification.add_unusual_modifier.description", "Add unusual modifier");
        add("the_vault.gear_modification.add_unusual_modifier.no_modifiers", "No additional modifiers available");
        add("the_vault.gear_modification.add_unusual_modifier.full", "You cannot add more unusual modifiers to this gear piece");
        add("the_vault.gear_modification.unfreeze_all.description", "Unfreeze all Frozen modifiers");
        add("the_vault.gear_modification.unfreeze_all.no_modifiers", "There are no frozen modifiers to unfreeze");
        add("the_vault.gear_modification.freeze_all.description", "Freezes a legendary, corrupted, greater, or unusual modifier");
        add("the_vault.gear_modification.freeze_all.no_modifiers", "There are no modifiers to freeze");
        add("the_vault.gear_modification.freeze_all.frozen", "There is already a frozen modifier");
        add("item.the_vault.companion", "Companion");
        add(new VaultDollCompletedAttribute(true), "is a completed Vault Doll", "is not a completed Vault Doll");
        add("create.item_attributes.has_unusual", "has an unusual modifier");
        add("create.item_attributes.has_unusual.inverted", "doesn't have an unusual modifier");
        add("create.item_attributes.has_divine", "is Divine");
        add("create.item_attributes.has_divine.inverted", "isn't Divine");
        add("create.item_attributes.unusual_prefix", "has an unusual \"%1$s\" prefix");
        add("create.item_attributes.unusual_prefix.inverted", "doesn't have an unusual \"%1$s\" prefix");
        add("create.item_attributes.unusual_suffix", "has an unusual \"%1$s\" suffix");
        add("create.item_attributes.unusual_suffix.inverted", "doesn't have an unusual \"%1$s\" suffix");
        add("create.item_attributes.offering_items", "is an Boss Rune with a Guaranteed \"%1$s\"");
        add("create.item_attributes.offering_items.inverted", "isn't an Boss Rune with a Guaranteed \"%1$s\"");
        add("create.item_attributes.offering_modifier", "has a \"%1$s\" Boss Rune modifier");
        add("create.item_attributes.offering_modifier.inverted", "doesn't have a \"%1$s\" Boss Rune modifier");
        add("create.item_attributes.targeted_mod_box_research", "is a Targeted Mod Box for the \"%1$s\" research");
        add("create.item_attributes.targeted_mod_box_research.inverted", "isn't a Targeted Mod Box for the \"%1$s\" research");
        add("create.item_attributes.antique_name", "is a \"%1$s\" Antique");
        add("create.item_attributes.antique_name.inverted", "isn't a \"%1$s\" Antique");
        add("create.item_attributes.rotten_offering", "is a rotten Boss Rune");
        add("create.item_attributes.rotten_offering.inverted", "isn't a rotten Boss Rune");
        add("create.item_attributes.etched_layout_type", "is an Etched Vault Layout with a \"%1$s\" layout");
        add("create.item_attributes.etched_layout_type.inverted", "isn't an Etched Vault Layout with a \"%1$s\" layout");
        add("create.item_attributes.etched_layout_tunnel", "is an Etched Vault Layout with a tunnel span of \"%1$s\"");
        add("create.item_attributes.etched_layout_tunnel.inverted", "isn't an Etched Vault Layout with a tunnel span of \"%1$s\"");
        add("create.item_attributes.etched_layout_value", "is an Etched Vault Layout with a value of \"%1$s\"");
        add("create.item_attributes.etched_layout_value.inverted", "isn't an Etched Vault Layout with a value of \"%1$s\"");
        add("create.item_attributes.gte_gate_pearl_size", "is a Gate Pearl with a size of \"%1$s\"");
        add("create.item_attributes.gte_gate_pearl_size.inverted", "is not a Gate Pearl with a size of \"%1$s\"");
        add("create.item_attributes.gte_gate_wave_count", "is a Gate Pearl with a wave count of at least \"%1$s\"");
        add("create.item_attributes.gte_gate_wave_count.inverted", "isn't a Gate Pearl with a wave count of at least \"%1$s\"");
        add("create.item_attributes.gte_gate_pearl_rewards", "is a Gate Pearl with a \"%1$s\" reward.");
        add("create.item_attributes.gte_gate_pearl_rewards.inverted", "isn't a Gate Pearl with a \"%1$s\" reward.");
        add("create.item_attributes.etching_set", "has a \"%1$s\" Etching");
        add("create.item_attributes.etching_set.inverted", "doesn't have a \"%1$s\" Etching");
        add("create.item_attributes.map_tier", "is a Vault Map with a tier of at least \"%1$s\"");
        add("create.item_attributes.map_tier.inverted", "isn't a Vault Map with a tier of at least \"%1$s\"");
        add("entity.the_vault.black_widow_boss", "Black Widow Boss");
        add("entity.the_vault.boogieman_boss", "Boogieman Boss");
        add("entity.the_vault.golem_boss", "Golem Boss");
        add("key.the_vault.quickselect.colossus", "Select and use ability: Colossus");
        add("key.the_vault.quickselect.expunge", "Select and use ability: Diffuse");
        add("key.the_vault.quickselect.necromancy", "Select and use ability: Necromancy");
        add("key.the_vault.quickselect.fangs", "Select and use ability: Fangs");
        add("woldsvaults.subtitle.saferspaces_proc", "Safer Spaces activated!");
        add("the_vault.gear_modification.tab.mythical", "Mythical");
        add("item.woldsvaults.pogominium_ingot", "POG-ominium Ingot");
        add("item.woldsvaults.infused_driftwood", "Infused Driftwood");
        add("item.woldsvaults.spark_of_inspiration", "Spark of Inspiration");
        add("block.woldsvaults.infused_driftwood_planks", "Infused Driftwood Planks");
        add("container.woldsvaults.infuser", "Vault Infuser");
        add("block.woldsvaults.chromatic_iron_vault_infuser", "Chromatic Iron Vault Infuser");
        add("block.woldsvaults.chromatic_steel_vault_infuser", "Chromatic Steel Vault Infuser");
        add("jei.category.woldsvaults.infuser", "Vault Infuser");
        add("item.woldsvaults.vault_diamond_nugget", "Vault Diamond Nugget");
        add("item.woldsvaults.chunk_of_power", "Chunk of Power");
        add("item.woldsvaults.soul_ichor", "Soul Ichor");
        add("item.woldsvaults.blazing_focus", "Blazing Focus");
        add("item.woldsvaults.suspension_focus", "Suspension Focus");
        add("block.woldsvaults.etching_shop_pedestal", "Etching Vendor Pedestal");
        add("block.woldsvaults.blacksmith_shop_pedestal", "Blacksmith Vendor Pedestal");
        add("block.woldsvaults.god_shop_pedestal", "God Vendor Pedestal");
        add("block.woldsvaults.rare_shop_pedestal", "Rare Vendor Pedestal");
        add("block.woldsvaults.omega_shop_pedestal", "Omega Vendor Pedestal");
        add("block.woldsvaults.spooky_shop_pedestal", "Spooky Vendor Pedestal");
        add("block.woldsvaults.gateway_channeling_block", "Gateway Channeling Beacon");
        add("item.woldsvaults.targeted_mod_box", "Targeted Mod Box");
        add("block.woldsvaults.mod_box_workstation", "Mod Box Workstation");
        add("item.woldsvaults.unidentified_gateway_pearl", "Unidentified Gateway Pearl");
        add("item.woldsvaults.prismatic_fiber", "Prismatic Fiber");
        add("block.woldsvaults.prismatic_fiber_block", "Block of Prismatic Fiber");
        add(ModBlocks.CHROMATIC_GOLD_BLOCK, "Block of Chromatic Gold");
        add(ModBlocks.SILVER_SCRAP_BLOCK, "Block of Silver Scrap");
        add(ModBlocks.VAULT_ESSENCE_BLOCK, "Block of Vault Essence");
        add(ModBlocks.CARBON_BLOCK, "Block of Carbon");
        add(ModBlocks.VAULT_INGOT_BLOCK, "Block of Vault Ingot");
        add(ModBlocks.VAULT_PLATING_BLOCK, "Block of Vault Plating");
        add(ModBlocks.OMEGA_POG_BLOCK, "Block of Omega Pog");
        add(ModBlocks.ECHO_POG_BLOCK, "Block of Echo Pog");
        add(ModBlocks.POG_BLOCK, "Block of Pog");
        add(ModBlocks.TIME_TRIAL_TROPHY_BLOCK, "Time Trial Trophy");
        add(ModBlocks.LOCKED_TREASURE_CONTAINER_BLOCK, "Locked Treasure Chest");
        add("block.woldsvaults.card_shop_pedestal", "Card Vendor Pedestal");
        add("block.woldsvaults.weaving_station", "Weaving Station");
        add("item.woldsvaults.recipe_blueprint", "Recipe Blueprint");
        add("item.woldsvaults.trinket_pouch", "Trinket Pouch");
        add("item.woldsvaults.chroma_core", "Chroma Core");
        add("item.woldsvaults.filter_necklace", "Filter Necklace");
        add("item.woldsvaults.crystal_seal_raid_rock_infinite_hard", "Brutal Raid Rock (Infinite)");
        add("item.the_vault.tool.material.nullite", "Nullite");
        add("block.the_vault.block_gem_wutodie_slab", "Wutodie Slab");
        add("block.the_vault.block_gem_wutodie_wall", "Wutodie Wall");
        add("block.the_vault.block_gem_wutodie_stairs", "Wutodie Stairs");
        add("item.woldsvaults.crystal_seal_alchemy", "Seal of the Alchemist");
        add("trinket_pouch.woldsvaults.standard", "Standard Trinket Pouch");
        add("trinket_pouch.woldsvaults.basic_alt_r", "Beginner's Trinket Pouch (Alt)");
        add("trinket_pouch.woldsvaults.basic_alt_g", "Beginner's Trinket Pouch (Alt)");
        add("trinket_pouch.woldsvaults.basic_classic", "Beginner's Trinket Pouch");
        add("trinket_pouch.woldsvaults.explorer", "Explorer's Trinket Pouch");
        add("trinket_pouch.woldsvaults.light", "Arcane Trinket Pouch");
        add("trinket_pouch.woldsvaults.wizard", "Wizard Trinket Pouch");
        add("trinket_pouch.woldsvaults.heavy", "Mercenary Trinket Pouch");
        add("trinket_pouch.woldsvaults.slayer", "Slayer Trinket Pouch");
        add("trinket_pouch.woldsvaults.looters_dream", "Looter's Dream Trinket Pouch");
        add("trinket_pouch.woldsvaults.warrior", "Warrior's Trinket Pouch");
        add("trinket_pouch.woldsvaults.hyper", "Hyper Trinket Pouch");
        add("trinket_pouch.woldsvaults.prismatic", "Prismatic Trinket Pouch");
        add("item.woldsvaults.trinket_pouch_slot_count", "+%1$s %2$s Slots");
        add(ModBlocks.PUZZLE_CUBE_BLOCK, "Puzzle Cube Block");
        add("woldsvaults.dweller_gate", "Dweller Duel");
        add("woldsvaults.medium_dweller_gate", "Dweller Invasion");
        add("woldsvaults.big_dweller_gate", "Dweller Apocalypse");
        add("woldsvaults.raid_gate", "Illager Incursion");
        add("woldsvaults.fungal_gate", "Fungal Infestation");
        add("woldsvaults.ghost_gate", "Haunted");
        add("woldsvaults.pirate_gate", "Pirate Brigade");
        add("woldsvaults.big_pirate_gate", "Pirate Apocalypse");
        add("woldsvaults.witch_gate", "Cruel Coven");
        add("woldsvaults.dungeon_gate", "Dungeon Incursion");
        add("woldsvaults.elite_gate", "Standard Elite Incursion");
        add("woldsvaults.guardian_gate", "Guardian Gauntlet");
        add("woldsvaults.thermal_gate", "Thermal Expansion");
        add("woldsvaults.glitch_gate", "§k??? ??? ???? ????");
        add("woldsvaults.tropical_gate", "Tropical Getaway");
        add("woldsvaults.cloud_gate", "Cloudy Day");
        add("woldsvaults.greed_assassin_gateway", "Greedy");

        add(ModBlocks.TENOS_PLANKS_SLAB, "Tenos Planks Slab");
        add(ModBlocks.TENOS_BRICKS_SLAB, "Tenos Bricks Slab");
        add(ModBlocks.TENOS_BRICK_CHISELED_SLAB, "Tenos Chiseled Bricks Slab");
        add(ModBlocks.TENOS_DARK_SMOOTH_BRICKS_SLAB, "Tenos Dark Smooth Bricks Slab");
        add(ModBlocks.TENOS_LIGHT_SMOOTH_BRICKS_SLAB, "Tenos Light Smooth Bricks Slab");
        add(ModBlocks.TENOS_GEM_BLOCK_SLAB, "Tenos Gem Block Slab");
        add(ModBlocks.TENOS_PLANKS_STAIRS, "Tenos Planks Stairs");
        add(ModBlocks.TENOS_BRICKS_STAIRS, "Tenos Bricks Stairs");
        add(ModBlocks.TENOS_BRICK_CHISELED_STAIRS, "Tenos Chiseled Bricks Stairs");
        add(ModBlocks.TENOS_DARK_SMOOTH_BRICKS_STAIRS, "Tenos Dark Smooth Bricks Stairs");
        add(ModBlocks.TENOS_LIGHT_SMOOTH_BRICKS_STAIRS, "Tenos Light Smooth Bricks Stairs");
        add(ModBlocks.TENOS_GEM_BLOCK_STAIRS, "Tenos Gem Block Stairs");

        add(ModBlocks.VELARA_BRICKS_SLAB, "Velara Bricks Slab");
        add(ModBlocks.VELARA_BRICK_CHISELED_SLAB, "Velara Chiseled Bricks Slab");
        add(ModBlocks.VELARA_DARK_SMOOTH_BRICKS_SLAB, "Velara Dark Smooth Bricks Slab");
        add(ModBlocks.VELARA_LIGHT_SMOOTH_BRICKS_SLAB, "Velara Light Smooth Bricks Slab");
        add(ModBlocks.VELARA_BRICKS_STAIRS, "Velara Bricks Stairs");
        add(ModBlocks.VELARA_BRICK_CHISELED_STAIRS, "Velara Chiseled Bricks Stairs");
        add(ModBlocks.VELARA_DARK_SMOOTH_BRICKS_STAIRS, "Velara Dark Smooth Bricks Stairs");
        add(ModBlocks.VELARA_LIGHT_SMOOTH_BRICKS_STAIRS, "Velara Light Smooth Bricks Stairs");
        add(ModBlocks.VELARA_GEM_BLOCK_SLAB, "Velara Gem Block Slab");
        add(ModBlocks.VELARA_GEM_BLOCK_STAIRS, "Velara Gem Block Stairs");

        add(ModBlocks.WENDARR_BRICKS_SLAB, "Wendarr Bricks Slab");
        add(ModBlocks.WENDARR_BRICK_CHISELED_SLAB, "Wendarr Chiseled Bricks Slab");
        add(ModBlocks.WENDARR_DARK_SMOOTH_BRICKS_SLAB, "Wendarr Dark Smooth Bricks Slab");
        add(ModBlocks.WENDARR_LIGHT_SMOOTH_BRICKS_SLAB, "Wendarr Light Smooth Bricks Slab");
        add(ModBlocks.WENDARR_BRICKS_STAIRS, "Wendarr Bricks Stairs");
        add(ModBlocks.WENDARR_BRICK_CHISELED_STAIRS, "Wendarr Chiseled Bricks Stairs");
        add(ModBlocks.WENDARR_DARK_SMOOTH_BRICKS_STAIRS, "Wendarr Dark Smooth Bricks Stairs");
        add(ModBlocks.WENDARR_LIGHT_SMOOTH_BRICKS_STAIRS, "Wendarr Light Smooth Bricks Stairs");
        add(ModBlocks.WENDARR_JEWEL_BLOCK_SLAB, "Wendarr Jewel Block Slab");
        add(ModBlocks.WENDARR_GEM_BLOCK_SLAB, "Wendarr Gem Block Slab");
        add(ModBlocks.WENDARR_JEWEL_BLOCK_STAIRS, "Wendarr Jewel Block Stairs");
        add(ModBlocks.WENDARR_GEM_BLOCK_STAIRS, "Wendarr Gem Block Stairs");

        add(ModBlocks.IDONA_BRICKS_SLAB, "Idona Bricks Slab");
        add(ModBlocks.IDONA_BRICK_CHISELED_SLAB, "Idona Chiseled Bricks Slab");
        add(ModBlocks.IDONA_DARK_SMOOTH_BRICKS_SLAB, "Idona Dark Smooth Bricks Slab");
        add(ModBlocks.IDONA_LIGHT_SMOOTH_BRICKS_SLAB, "Idona Light Smooth Bricks Slab");
        add(ModBlocks.IDONA_BRICKS_STAIRS, "Idona Bricks Stairs");
        add(ModBlocks.IDONA_BRICK_CHISELED_STAIRS, "Idona Chiseled Bricks Stairs");
        add(ModBlocks.IDONA_DARK_SMOOTH_BRICKS_STAIRS, "Idona Dark Smooth Bricks Stairs");
        add(ModBlocks.IDONA_LIGHT_SMOOTH_BRICKS_STAIRS, "Idona Light Smooth Bricks Stairs");
        add(ModBlocks.IDONA_GEM_BLOCK_STAIRS, "Idona Gem Block Stairs");
        add(ModBlocks.IDONA_GEM_BLOCK_SLAB, "Idona Gem Block Slab");



        ModItems.COLORED_UNOBTANIUMS.forEach(((dyeColor, basicItem) -> {
            add(basicItem, StringUtils.convertToTitleCase(dyeColor.getSerializedName()) + " Unobtanium");
        }));

        ModBlocks.COLORED_UNOBTANIUMS.forEach(((dyeColor, basicItem) -> {
            add(basicItem, StringUtils.convertToTitleCase(dyeColor.getSerializedName()) + " Unobtanium Block");
        }));

        add(ModBlocks.RAINBOW_UNOBTANIUM, "Rainbow Unobtanium Block");
        add(ModItems.RAINBOW_UNOBTANIUM, "Rainbow Unobtanium");

        EnchantedEventsRegistry.registerAllBuiltInEvents();
        ModVaultEvents.init();

        VaultEventSystem.getAllEvents().forEach(this::add);

        addMilestoneNames();
        addMilestoneDescriptions();
        addGreedScreenText();

        REGISTERED_LANGUAGE_KEYS.forEach(this::add);

        ModBlocks.CUSTOM_VAULT_CRATES.forEach((s, crateBlock) -> {
            add(crateBlock, StringUtils.convertToTitleCase(s) + " Vault Crate");
        });

        ModCompressibleBlocks.getRegisteredBlocks().forEach((k, v) -> {
            for (int i = 0; i < v.size(); i ++) {
                add(v.get(i).get(), "Compressed " + (k.isBlockOf() ? "Block of " : "") + StringUtils.convertToTitleCase(k.name()) + " ("+(i+1)+"x)");
            }
        });

    }

    /**
     * Milestone display names and the chat lines the milestone engine sends on a tier completion.
     */
    private void addMilestoneNames() {
        add("milestone.woldsvaults.completed", "Milestone complete: %1$s - collect your reputation from Mr. Greedy");
        add("milestone.woldsvaults.tier_completed", "Milestone: %1$s (tier %2$s of %3$s) - collect your reputation from Mr. Greedy");
        add("milestone.woldsvaults.reputation", "%1$s Greed Reputation waiting at Mr. Greedy");
        add("milestone.woldsvaults.claimed", "Collected %2$s Greed Reputation from %1$s");
        add("milestone.woldsvaults.living_looter", "Living Looter");
        add("milestone.woldsvaults.ornate_looter", "Ornate Looter");
        add("milestone.woldsvaults.gilded_looter", "Gilded Looter");
        add("milestone.woldsvaults.wooden_looter", "Wooden Looter");
        add("milestone.woldsvaults.treasure_hunter", "Treasure Hunter");
        add("milestone.woldsvaults.shop_hunter", "Shop Hunter");
        add("milestone.woldsvaults.diggy_diggy_jewel", "Diggy Diggy Jewel");
        add("milestone.woldsvaults.amazon_worker", "Amazon Worker");
        add("milestone.woldsvaults.nullified", "Nullified");
        add("milestone.woldsvaults.dedicated_looter", "Dedicated Looter");
        add("milestone.woldsvaults.bingo", "Bingo!!!");
        add("milestone.woldsvaults.drink_up", "Drink Up");
        add("milestone.woldsvaults.brutalized", "Brutalized");
        add("milestone.woldsvaults.scavingo", "Bingo...?");
        add("milestone.woldsvaults.chaos_objectives", "AHHHHH");
        add("milestone.woldsvaults.hyperion", "Hyperion");
        add("milestone.woldsvaults.alchemist", "Alchemist");
        add("milestone.woldsvaults.vaults_hunted", "Vaults Hunted");
        add("milestone.woldsvaults.light_the_flame", "Light the Flame");
        add("milestone.woldsvaults.i_will_survive", "I Will Survive");
        add("milestone.woldsvaults.runic_ritual", "Runic Ritual");
        add("milestone.woldsvaults.eternal_darkness", "Eternal Darkness");
        add("milestone.woldsvaults.seen_it_all", "Seen It All");
        add("milestone.woldsvaults.royale_paine", "Royale Paine");
        add("milestone.woldsvaults.stairway_to_heaven", "Stairway to Heaven");
        add("milestone.woldsvaults.slayerrr", "SLAYERRR");
        add("milestone.woldsvaults.hack_n_slash", "Hack'n Slash");
        add("milestone.woldsvaults.archmage", "Archmage");
        add("milestone.woldsvaults.spell_spammer", "Spell Spammer");
        add("milestone.woldsvaults.electric_conduit", "Electric Conduit");
        add("milestone.woldsvaults.master_of_chains", "Master of Chains");
        add("milestone.woldsvaults.defense", "Defense!");
        add("milestone.woldsvaults.woosh", "Woosh");
        add("milestone.woldsvaults.five_leaf_clover", "Five Leaf Clover");
        add("milestone.woldsvaults.boom", "BOOM");
        add("milestone.woldsvaults.dungeoneer", "Dungeoneer");
        add("milestone.woldsvaults.villain", "Villain");
        add("milestone.woldsvaults.flawless_victory", "Flawless Victory");
        add("milestone.woldsvaults.fail_vaults", "If You Fail Once, Try Again");
        add("milestone.woldsvaults.master_smith", "Master Smith");
        add("milestone.woldsvaults.idonas_champion", "Idona's Champion");
        add("milestone.woldsvaults.priest_of_velara", "Priest of Velara");
        add("milestone.woldsvaults.tenos_right_hand", "Tenos' Right Hand");
        add("milestone.woldsvaults.wendarrs_timekeeper", "Wendarr's Timekeeper");
        add("milestone.woldsvaults.explorer", "Explorer");
        add("milestone.woldsvaults.i_live_here_now", "I Live Here Now");
        add("milestone.woldsvaults.legendary", "Legendary!");
        add("milestone.woldsvaults.challenged", "Challenged");
        add("milestone.woldsvaults.vault_of_vaults", "The Vault of Vaults");
        add("milestone.woldsvaults.wanted_criminal", "Wanted Criminal");
        add("milestone.woldsvaults.archeologist", "Archeologist");
        add("milestone.woldsvaults.send_a_prayer", "Send a Prayer");
        add("milestone.woldsvaults.born_again", "Born Again");
        add("milestone.woldsvaults.pal_trainer", "Pal Trainer");
        add("milestone.woldsvaults.vault_veteran", "Vault Veteran");
        add("milestone.woldsvaults.unstable_shuffle", "Unstable Shuffle");
        add("milestone.woldsvaults.pitch_black", "Pitch Black");
        add("milestone.woldsvaults.trapped", "Trapped");
        add("milestone.woldsvaults.ballistic_blackout", "Ballistic Blackout");
        add("milestone.woldsvaults.rune_master", "Rune Master");
        add("milestone.woldsvaults.elixir_of_doom", "Elixir of Doom");
        add("milestone.woldsvaults.collectathon", "Collectathon");
        add("milestone.woldsvaults.royale_king", "Royale King");
        add("milestone.woldsvaults.gone_in_60_seconds", "Gone in 60 Seconds");
        add("milestone.woldsvaults.survival_of_the_fittest", "Survival of the Fittest");
        add("milestone.woldsvaults.the_pacifist", "The Pacifist");
        add("milestone.woldsvaults.gods_challenge", "God's Challenge");
        add("milestone.woldsvaults.luckiest_win", "Luckiest Win");
        add("milestone.woldsvaults.big_bad_brew", "Big Bad Brew");
        add("milestone.woldsvaults.the_speedrunner", "The Speedrunner");
        add("milestone.woldsvaults.time_you_say", "Time You Say");
        add("milestone.woldsvaults.chaos_chaos_chaos", "Chaos Chaos Chaos");
        add("milestone.woldsvaults.the_speed_blackout", "The Speed Blackout");
        add("milestone.woldsvaults.frenzy_adventures", "Frenzy Adventures");
        add("milestone.woldsvaults.rage_cage", "Rage Cage");
        add("milestone.woldsvaults.celebrations", "Celebrations");
    }

    /**
     * Requirement lines shown under each achievement name on the greed screens. One per
     * milestone id, naming the quantity its counter tracks.
     */
    private void addMilestoneDescriptions() {
        add("milestone.woldsvaults.living_looter.desc", "Living chests looted");
        add("milestone.woldsvaults.ornate_looter.desc", "Ornate chests looted");
        add("milestone.woldsvaults.gilded_looter.desc", "Gilded chests looted");
        add("milestone.woldsvaults.wooden_looter.desc", "Wooden chests looted");
        add("milestone.woldsvaults.treasure_hunter.desc", "Treasure rooms opened");
        add("milestone.woldsvaults.shop_hunter.desc", "Vendoor shop rooms opened");
        add("milestone.woldsvaults.diggy_diggy_jewel.desc", "Ore blocks mined in vaults");
        add("milestone.woldsvaults.amazon_worker.desc", "Wooden vault barrels looted");
        add("milestone.woldsvaults.nullified.desc", "Nullite ore blocks mined");
        add("milestone.woldsvaults.dedicated_looter.desc", "Loot 25k of every chest type in one vault");
        add("milestone.woldsvaults.bingo.desc", "Bingo lines completed");
        add("milestone.woldsvaults.drink_up.desc", "Elixir collected in elixir vaults");
        add("milestone.woldsvaults.brutalized.desc", "Brutal boss wave mobs killed");
        add("milestone.woldsvaults.scavingo.desc", "Scavenger bingo lines completed");
        add("milestone.woldsvaults.chaos_objectives.desc", "Chaos tasks completed");
        add("milestone.woldsvaults.hyperion.desc", "Hyper crate tiers earned from bosses");
        add("milestone.woldsvaults.alchemist.desc", "Alchemy progress, in percent");
        add("milestone.woldsvaults.vaults_hunted.desc", "Vaults completed");
        add("milestone.woldsvaults.light_the_flame.desc", "Haunted braziers lit");
        add("milestone.woldsvaults.i_will_survive.desc", "Time survived in survival vaults, in ticks");
        add("milestone.woldsvaults.runic_ritual.desc", "Rune boss fights completed");
        add("milestone.woldsvaults.eternal_darkness.desc", "Obelisks activated in corrupted vaults");
        add("milestone.woldsvaults.seen_it_all.desc", "Distinct vault objectives completed");
        add("milestone.woldsvaults.royale_paine.desc", "Vault Royale runs completed");
        add("milestone.woldsvaults.stairway_to_heaven.desc", "Ascension vaults completed");
        add("milestone.woldsvaults.slayerrr.desc", "Mobs killed inside vaults");
        add("milestone.woldsvaults.hack_n_slash.desc", "Attack damage dealt to mobs");
        add("milestone.woldsvaults.archmage.desc", "Ability damage dealt to mobs");
        add("milestone.woldsvaults.spell_spammer.desc", "Mana spent on abilities");
        add("milestone.woldsvaults.electric_conduit.desc", "Mobs killed with lightning");
        add("milestone.woldsvaults.master_of_chains.desc", "Mobs killed with chaining attacks");
        add("milestone.woldsvaults.defense.desc", "Attacks blocked");
        add("milestone.woldsvaults.woosh.desc", "Attacks dodged");
        add("milestone.woldsvaults.five_leaf_clover.desc", "Lucky hits triggered");
        add("milestone.woldsvaults.boom.desc", "Mobs killed with explosions");
        add("milestone.woldsvaults.dungeoneer.desc", "Dungeon bosses killed");
        add("milestone.woldsvaults.villain.desc", "Cockroaches killed");
        add("milestone.woldsvaults.flawless_victory.desc", "Vaults completed without taking damage");
        add("milestone.woldsvaults.fail_vaults.desc", "Vaults failed");
        add("milestone.woldsvaults.master_smith.desc", "Max out vault forge proficiency");
        add("milestone.woldsvaults.idonas_champion.desc", "Highest Idona alignment level reached");
        add("milestone.woldsvaults.priest_of_velara.desc", "Highest Velara alignment level reached");
        add("milestone.woldsvaults.tenos_right_hand.desc", "Highest Tenos alignment level reached");
        add("milestone.woldsvaults.wendarrs_timekeeper.desc", "Highest Wendarr alignment level reached");
        add("milestone.woldsvaults.explorer.desc", "Tiered vault maps completed");
        add("milestone.woldsvaults.i_live_here_now.desc", "Time spent inside vaults, in ticks");
        add("milestone.woldsvaults.legendary.desc", "Omega rooms discovered");
        add("milestone.woldsvaults.challenged.desc", "Challenge rooms completed");
        add("milestone.woldsvaults.vault_of_vaults.desc", "One vault: 10k mobs, 4k chests, 1k ores");
        add("milestone.woldsvaults.wanted_criminal.desc", "Black market trades made");
        add("milestone.woldsvaults.archeologist.desc", "Ancient uniques identified");
        add("milestone.woldsvaults.send_a_prayer.desc", "God altars completed");
        add("milestone.woldsvaults.born_again.desc", "Phoenix revives used");
        add("milestone.woldsvaults.pal_trainer.desc", "Distinct companions raised to max level");
        add("milestone.woldsvaults.vault_veteran.desc", "Tiers cleared on every other achievement");
        add("milestone.woldsvaults.unstable_shuffle.desc", "Complete the Unstable Shuffle challenge");
        add("milestone.woldsvaults.pitch_black.desc", "Complete the Pitch Black challenge");
        add("milestone.woldsvaults.trapped.desc", "Complete the Trapped challenge");
        add("milestone.woldsvaults.ballistic_blackout.desc", "Complete the Ballistic Blackout challenge");
        add("milestone.woldsvaults.rune_master.desc", "Complete the Rune Master challenge");
        add("milestone.woldsvaults.elixir_of_doom.desc", "Complete the Elixir of Doom challenge");
        add("milestone.woldsvaults.collectathon.desc", "Complete the Collectathon challenge");
        add("milestone.woldsvaults.royale_king.desc", "Complete the Royale King challenge");
        add("milestone.woldsvaults.gone_in_60_seconds.desc", "Complete the Gone in 60 Seconds challenge");
        add("milestone.woldsvaults.survival_of_the_fittest.desc", "Complete the Survival of the Fittest challenge");
        add("milestone.woldsvaults.the_pacifist.desc", "Complete the Pacifist challenge");
        add("milestone.woldsvaults.gods_challenge.desc", "Complete God's Challenge");
        add("milestone.woldsvaults.luckiest_win.desc", "Complete the Luckiest Win challenge");
        add("milestone.woldsvaults.big_bad_brew.desc", "Complete the Big Bad Brew challenge");
        add("milestone.woldsvaults.the_speedrunner.desc", "Complete the Speedrunner challenge");
        add("milestone.woldsvaults.time_you_say.desc", "Complete the Time You Say challenge");
        add("milestone.woldsvaults.chaos_chaos_chaos.desc", "Complete the Chaos Chaos Chaos challenge");
        add("milestone.woldsvaults.the_speed_blackout.desc", "Complete the Speed Blackout challenge");
        add("milestone.woldsvaults.frenzy_adventures.desc", "Complete the Frenzy Adventures challenge");
        add("milestone.woldsvaults.rage_cage.desc", "Complete the Rage Cage challenge");
        add("milestone.woldsvaults.celebrations.desc", "Complete the Celebrations challenge");
    }

    /**
     * Every label, tooltip, rank name and rank-up unlock line on the greed screens.
     */
    private void addGreedScreenText() {
        add("screen.woldsvaults.greed.title", "Greed");
        add("screen.woldsvaults.greed.tab.main", "Main");
        add("screen.woldsvaults.greed.tab.offense", "Offense");
        add("screen.woldsvaults.greed.tab.loot", "Loot");
        add("screen.woldsvaults.greed.tab.vault", "Vault");
        add("screen.woldsvaults.greed.tab.misc", "Misc");
        add("screen.woldsvaults.greed.tab.challenge", "Challenge");
        add("screen.woldsvaults.greed.gain_on_rank_up", "Gain on rank up");
        add("screen.woldsvaults.greed.pinned_task", "Pinned task");
        add("screen.woldsvaults.greed.pinned_task.empty", "Nothing pinned. Pin an achievement from any tab to track it here.");
        add("screen.woldsvaults.greed.take_trial", "Take Trial");
        add("screen.woldsvaults.greed.take_trial.hyper", "A toned-down Hyper Vault. Clear the required boss cycles to pass.");
        add("screen.woldsvaults.greed.take_trial.vessel", "A fight with the Vessel. Deal the required damage before the timer runs out.");
        add("screen.woldsvaults.greed.take_trial.reward", "Reward: rank up and %1$s greed coins");
        add("screen.woldsvaults.greed.take_trial.none", "No trial remains - further ranks are earned with reputation alone.");
        add("screen.woldsvaults.greed.take_trial.locked.reputation", "%1$s more reputation to unlock the trial");
        add("screen.woldsvaults.greed.take_trial.locked.god", "Requires god level %1$s (best: %2$s)");
        add("screen.woldsvaults.greed.shop_reroll_cost", "Shop reroll cost: %1$s tickets");
        add("screen.woldsvaults.greed.shop_reroll_cost.tooltip", "Rerolling the greed shop costs Greedy Tickets, and the price rises every second reroll. The shop restocks and the price resets on the black market's clock.");
        add("screen.woldsvaults.greed.active_god", "Active god tree: %1$s (level %2$s)");
        add("screen.woldsvaults.greed.active_god.none", "Active god tree: None");
        add("screen.woldsvaults.greed.list.empty", "No achievements in this category");
        add("screen.woldsvaults.greed.claim", "Claim");
        add("screen.woldsvaults.greed.claim.tooltip", "Collect the reputation this achievement has banked");
        add("screen.woldsvaults.greed.claim.tooltip.player", "Reputation is collected from Mr. Greedy");
        add("screen.woldsvaults.greed.pin.pin", "Pin");
        add("screen.woldsvaults.greed.pin.unpin", "Unpin");
        add("screen.woldsvaults.greed.pin.pin.tooltip", "Track this achievement on the main greed screen. You may pin one at a time.");
        add("screen.woldsvaults.greed.pin.unpin.tooltip", "Stop tracking this achievement");
        add("screen.woldsvaults.greed.row.rep", "+%1$s Rep");
        add("screen.woldsvaults.greed.row.rep_list", "Rep: ");
        add("screen.woldsvaults.greed.rank.none", "Unranked");
        add("screen.woldsvaults.greed.rank.1", "Scavenger 1");
        add("screen.woldsvaults.greed.rank.2", "Scavenger 2");
        add("screen.woldsvaults.greed.rank.3", "Scavenger 3");
        add("screen.woldsvaults.greed.rank.4", "Looter 1");
        add("screen.woldsvaults.greed.rank.5", "Looter 2");
        add("screen.woldsvaults.greed.rank.6", "Looter 3");
        add("screen.woldsvaults.greed.rank.7", "Hunter 1");
        add("screen.woldsvaults.greed.rank.8", "Hunter 2");
        add("screen.woldsvaults.greed.rank.9", "Hunter 3");
        add("screen.woldsvaults.greed.rank.10", "Master 1");
        add("screen.woldsvaults.greed.rank.11", "Master 2");
        add("screen.woldsvaults.greed.rank.12", "Master 3");
        add("screen.woldsvaults.greed.rank.13", "Champion 1");
        add("screen.woldsvaults.greed.rank.14", "Champion 2");
        add("screen.woldsvaults.greed.rank.15", "Champion 3");
        add("screen.woldsvaults.greed.rank.16", "Legend");
        add("screen.woldsvaults.greed.rank.legend_plus", "Legend +%1$s");
        add("screen.woldsvaults.greed.unlock.1", "Unlocks the greed cauldron, Mr. Greedy, etchings, prestige and greed medallions");
        add("screen.woldsvaults.greed.unlock.2", "+1 shop slot, unlocks tier 1 greed cards");
        add("screen.woldsvaults.greed.unlock.3", "+1 shop slot, unlocks vault maps of tiers 1 to 3");
        add("screen.woldsvaults.greed.unlock.4", "+1 shop slot, unlocks god alignments, greedy companion relics and challenges");
        add("screen.woldsvaults.greed.unlock.5", "+1 shop slot, unlocks some Greater Cores and tier 4 maps");
        add("screen.woldsvaults.greed.unlock.6", "+1 shop slot, unlocks tier 2 greed cards");
        add("screen.woldsvaults.greed.unlock.7", "+1 shop slot, unlocks tier 5 maps and ancient uniques. Needs level 2 with any god.");
        add("screen.woldsvaults.greed.unlock.8", "+1 shop slot, unlocks all Greater Cores and the Mystery Deck");
        add("screen.woldsvaults.greed.unlock.9", "+1 shop slot, unlocks level 2 greedy relics and tier 3 greed cards");
        add("screen.woldsvaults.greed.unlock.10", "+1 shop slot, unlocks tier 6 maps, raises ancient drop chance. Needs level 4 with any god.");
        add("screen.woldsvaults.greed.unlock.11", "+1 shop slot, unlocks stronger greedy catalysts");
        add("screen.woldsvaults.greed.unlock.12", "+1 shop slot, unlocks level 3 greedy relics");
        add("screen.woldsvaults.greed.unlock.13", "+1 shop slot, unlocks tier 4 greed cards. Needs level 6 with any god.");
        add("screen.woldsvaults.greed.unlock.14", "+1 shop slot, raises ancient drop chance");
        add("screen.woldsvaults.greed.unlock.15", "+1 shop slot, -10% greed shop cost");
        add("screen.woldsvaults.greed.unlock.16", "+1 shop slot. Needs level 8 with any god.");
        add("screen.woldsvaults.greed.unlock.legend_plus", "+1 shop slot per further 250 reputation");
        add("screen.woldsvaults.gods.title", "Gods");
        add("screen.woldsvaults.gods.uncharted", "%1$s's constellation has not been charted yet.");
                add("item.woldsvaults.idona_god_neuralizer", "Idona God Neuralizer");
        add("item.woldsvaults.velara_god_neuralizer", "Velara God Neuralizer");
        add("item.woldsvaults.tenos_god_neuralizer", "Tenos God Neuralizer");
        add("item.woldsvaults.wendarr_god_neuralizer", "Wendarr God Neuralizer");
        add("item.woldsvaults.red_vault_essence", "Red Vault Essence");
        add("item.woldsvaults.mythic_vault_charm", "Vault God Charm");
        add("item.woldsvaults.mythic_vault_charm.idona", "Idona's Charm");
        add("item.woldsvaults.mythic_vault_charm.velara", "Velara's Charm");
        add("item.woldsvaults.mythic_vault_charm.tenos", "Tenos' Charm");
        add("item.woldsvaults.mythic_vault_charm.wendarr", "Wendarr's Charm");
        add("key.woldsvaults.toggle_charm_blessing", "Toggle Charm Blessing");
    }

    public static final LinkedHashMap<String, String> REGISTERED_LANGUAGE_KEYS = new LinkedHashMap<>();
}
