package xyz.iwolfking.woldsvaults.init;

import iskallia.vault.VaultMod;
import net.minecraft.ChatFormatting;
import net.minecraft.network.chat.TextColor;
import net.minecraft.network.chat.TextComponent;
import net.minecraft.network.chat.TranslatableComponent;
import net.minecraft.sounds.SoundEvents;
import net.minecraft.sounds.SoundSource;
import net.minecraft.world.effect.MobEffects;
import net.minecraft.world.entity.EntityType;
import net.minecraft.world.level.Explosion;
import net.minecraft.world.level.block.Blocks;
import xyz.iwolfking.woldsvaults.WoldsVaults;
import xyz.iwolfking.woldsvaults.api.core.vault_events.VaultEventSystem;
import xyz.iwolfking.woldsvaults.api.core.vault_events.impl.tasks.*;
import xyz.iwolfking.woldsvaults.api.core.vault_events.lib.EventTag;
import xyz.iwolfking.woldsvaults.api.core.vault_events.VaultEvent;
import xyz.iwolfking.woldsvaults.api.util.ref.Effect;

public class ModVaultEvents {


    public static void init() {
        VaultEventSystem.register(WoldsVaults.id("crate_tier"), new VaultEvent.Builder()
                .tag(EventTag.POSITIVE)
                .tag(EventTag.ADDS_MODIFIER)
                .displayType(VaultEvent.EventDisplayType.NONE)
                .color(TextColor.fromLegacyFormat(ChatFormatting.GOLD))
                .task(new VaultModifierTask(VaultMod.id("crate_tier"), 1))
                .build("Crate Tier", new TextComponent("Adds a crate tier to the vault.")));
        VaultEventSystem.register(WoldsVaults.id("tombstone_event"), new VaultEvent.Builder()
                .tag(EventTag.TOMBSTONE)
                .displayType(VaultEvent.EventDisplayType.NONE)
                        .task(new WeightedTask.Builder()
                                .task(new TaskGroup.Builder()
                                        .task(new SpawnMobTask.Builder()
                                            .entity(iskallia.vault.init.ModEntities.ELITE_ZOMBIE, 2.0)
                                            .entity(iskallia.vault.init.ModEntities.ELITE_SKELETON, 7.0)
                                            .entity(iskallia.vault.init.ModEntities.ELITE_WITHER_SKELETON, 1.0)
                                            .spawnRanges(1.0, 4.0)
                                            .build()
                                        )
                                        .task(new MessageTask(VaultEvent.EventDisplayType.ACTION_BAR, new TranslatableComponent("vault_event.woldsvaults.tombstone_elite").withStyle(ChatFormatting.DARK_PURPLE)))
                                        .build(), 4.0)
                                .task(new PlaySoundTask(SoundEvents.AMBIENT_CAVE, 1.0F, 0.6F, SoundSource.AMBIENT), 25.0)
                                .task(new TaskGroup.Builder()
                                        .task(new PlayerMobEffectTask.Builder()
                                                .effect(MobEffects.WITHER, 1, 200)
                                                .build()
                                        )
                                        .task(new PlaySoundTask(SoundEvents.SOUL_ESCAPE))
                                        .task(new MessageTask(VaultEvent.EventDisplayType.ACTION_BAR, new TranslatableComponent("vault_event.woldsvaults.tombstone_wither").withStyle(ChatFormatting.DARK_RED)))
                                        .build(),10.0)
                                .task(new TaskGroup.Builder()
                                        .task(new PlayerMobEffectTask.Builder()
                                                .effect(MobEffects.DIG_SLOWDOWN, 1, 300)
                                                .effect(MobEffects.MOVEMENT_SLOWDOWN, 2, 400)
                                                .build()
                                        )
                                        .task(new PlaySoundTask(SoundEvents.AMBIENT_CAVE))
                                        .task(new MessageTask(VaultEvent.EventDisplayType.ACTION_BAR, new TranslatableComponent("vault_event.woldsvaults.tombstone_weaken").withStyle(ChatFormatting.DARK_RED)))
                                        .build(),10.0)
                                .task(new TaskGroup.Builder()
                                        .task(new ExplosionTask(5.0F, Explosion.BlockInteraction.BREAK, true))
                                        .task(new MessageTask(VaultEvent.EventDisplayType.ACTION_BAR, new TranslatableComponent("vault_event.woldsvaults.tombstone_explode").withStyle(ChatFormatting.RED)))
                                        .build(),10.0)
                                .task(new TaskGroup.Builder()
                                        .task(new VaultModifierTask(VaultMod.id("cake_haunted"), 1))
                                        .task(new MessageTask(VaultEvent.EventDisplayType.CHAT_MESSAGE_TARGET, new TranslatableComponent("vault_event.woldsvaults.tombstone_soul_shard_increase").withStyle(ChatFormatting.LIGHT_PURPLE)))
                                        .task(new PlaySoundTask(SoundEvents.AMBIENT_CAVE))
                                        .build(), 10.0)
                                .task(new TaskGroup.Builder()
                                        .task(new VaultModifierTask(VaultMod.id("haunted_mansion"), 1, 1800))
                                        .task(new MessageTask(VaultEvent.EventDisplayType.ACTION_BAR, new TranslatableComponent("vault_event.woldsvaults.tombstone_haunted").withStyle(ChatFormatting.DARK_GRAY)))
                                        .task(new PlaySoundTask(SoundEvents.AMBIENT_CAVE))
                                        .build(), 2.0)
                                .task(new TaskGroup.Builder()
                                        .task(new VaultModifierTask(VaultMod.id("ethereal_mobs"), 1, 900))
                                        .task(new MessageTask(VaultEvent.EventDisplayType.ACTION_BAR, new TranslatableComponent("vault_event.woldsvaults.tombstone_ethereal").withStyle(ChatFormatting.DARK_AQUA)))
                                        .task(new PlaySoundTask(SoundEvents.AMBIENT_CAVE))
                                        .build(), 4.0)
                                .task(new TaskGroup.Builder()
                                        .task(new SpawnMobTask.Builder()
                                                .entity(ModEntities.GREEN_GHOST, 1)
                                                .entity(ModEntities.BROWN_GHOST, 1)
                                                .entity(ModEntities.RED_GHOST, 1)
                                                .entity(ModEntities.BLUE_GHOST, 1)
                                                .entity(ModEntities.YELLOW_GHOST, 1)
                                                .amount(3, 1)
                                                .amount(5, 1)
                                                .effect(new Effect(MobEffects.MOVEMENT_SPEED, 2, 400), 1)
                                                .build()
                                        )
                                        .task(new PlaySoundTask(SoundEvents.SOUL_ESCAPE))
                                        .task(new MessageTask(VaultEvent.EventDisplayType.ACTION_BAR, new TranslatableComponent("vault_event.woldsvaults.tombstone_spirits").withStyle(ChatFormatting.AQUA)))
                                        .build(),10.0)
                                .task(new TaskGroup.Builder()
                                        .task(new SpawnMobTask.Builder()
                                                .entity(iskallia.vault.init.ModEntities.T3_ZOMBIE, 1)
                                                .amount(1, 1)
                                                .effect(new Effect(MobEffects.MOVEMENT_SPEED, 2, 400), 1)
                                                .effect(new Effect(MobEffects.DAMAGE_RESISTANCE, 2, 400), 1)
                                                .effect(new Effect(MobEffects.DAMAGE_BOOST, 2, 400), 1)
                                                .spawnRanges(1.0, 4.0)
                                                .build()
                                        )
                                        .task(new PlaySoundTask(SoundEvents.AMBIENT_CAVE))
                                        .task(new MessageTask(VaultEvent.EventDisplayType.ACTION_BAR, new TranslatableComponent("vault_event.woldsvaults.tombstone_zombie").withStyle(ChatFormatting.DARK_GREEN)))
                                        .build(),15.0)
                                .task(new TaskGroup.Builder()
                                        .task(new SpawnMobTask.Builder()
                                                .entity(iskallia.vault.init.ModEntities.T3_SKELETON, 1)
                                                .entity(iskallia.vault.init.ModEntities.T3_BLOOD_SKELETON, 1)
                                                .entity(iskallia.vault.init.ModEntities.T3_CAVE_SKELETON, 1)
                                                .entity(iskallia.vault.init.ModEntities.T3_PLASTIC_SKELETON, 1)
                                                .entity(iskallia.vault.init.ModEntities.T3_WITHER_SKELETON, 1)
                                                .entity(iskallia.vault.init.ModEntities.T3_SKELETON_PIRATE, 1)
                                                .amount(1, 1)
                                                .amount(2, 1)
                                                .amount(3, 1)
                                                .effect(new Effect(MobEffects.MOVEMENT_SPEED, 2, 400), 1)
                                                .effect(new Effect(MobEffects.DAMAGE_BOOST, 2, 400), 1)
                                                .effect(new Effect(MobEffects.DAMAGE_RESISTANCE, 2, 400), 1)
                                                .spawnRanges(1.0, 4.0)
                                                .build()
                                        )
                                        .task(new PlaySoundTask(SoundEvents.AMBIENT_CAVE))
                                        .task(new MessageTask(VaultEvent.EventDisplayType.ACTION_BAR, new TranslatableComponent("vault_event.woldsvaults.tombstone_skeleton").withStyle(ChatFormatting.GRAY)))
                                        .build(),20.0)
                                .task(new TaskGroup.Builder()
                                        .task(new SpawnMobTask.Builder()
                                                .entity(EntityType.SKELETON_HORSE, 1)
                                                .amount(1, 1)
                                                .spawnRanges(1.0, 4.0)
                                                .build()
                                        )
                                        .task(new PlaySoundTask(SoundEvents.AMBIENT_CAVE))
                                        .task(new MessageTask(VaultEvent.EventDisplayType.ACTION_BAR, new TranslatableComponent("vault_event.woldsvaults.tombstone_horse").withStyle(ChatFormatting.LIGHT_PURPLE)))
                                        .build(),2.0)
                                .build()

                        )
                        .task(new DelayTask(20))
                        .task(new BlockConversionTask.Builder()
                                .replacementBlock(Blocks.DIRT.defaultBlockState(), 4)
                                .replacementBlock(Blocks.ROOTED_DIRT.defaultBlockState(), 2)
                                .replacementBlock(Blocks.STONE.defaultBlockState(), 1)
                                .replacementBlock(Blocks.COARSE_DIRT.defaultBlockState(), 2)
                                .replacementBlock(Blocks.ANDESITE.defaultBlockState(), 1)
                                .replacementBlock(Blocks.PODZOL.defaultBlockState(), 2)
                                .build(block -> block.equals(Blocks.BEDROCK)))
                        .task(new DelayTask(10))
                        .task(new BlockConversionTask.Builder().build(block -> block.equals(Blocks.BARRIER) || block.equals(Blocks.LECTERN)))

                .build("Tombstone", new TextComponent("Possible events that can occur when breaking a Tombstone.")));
    }
}
